### ISSUE TITLE
Add Footer Component

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#1]
**Add Footer In Layout Component By Which It Can Common In All But We Implemented The Header With Relative Property The Whole Content Render Beyond That Hero And Other Component Which Have Absolute Property So Write The Footer In Such A Way That It Can Show In Bottom Of Page.**

**Comment by antidude900** [comment]
Can you give this task to me?

**Comment by antidude900** [comment]
I am having problem with setting up the project due to missing env values. Could you please provide sample env?

**Comment by TejasNasre** [comment]
@antidude900 you just want to add footer now .env.example will be push soon with setup guide and rules

**Comment by TejasNasre** [comment]
merge with dev branch after completing the issue

**Comment by antidude900** [comment]
When i execute npm run build, this error occurs:
![image](https://github.com/user-attachments/assets/865f2967-4453-4bac-b68b-ba2caf7174c4)

**Comment by TejasNasre** [comment]
you are adding just static footer make PR if complete  don't run build i will fix just make sure to avoid errors

**Comment by antidude900** [comment]
give me an hour

**Comment by TejasNasre** [comment]
@antidude900 are you working on it ?

**Comment by antidude900** [comment]
yeah i want to discuss something

**Comment by antidude900** [comment]
Cant we make the header absolute top-0 instead of the hero componenet?

**Comment by antidude900** [comment]
The hero component as being absolute top- 0 is always overlapping the footer and the footer is next to the header

**Comment by antidude900** [comment]
just making the header absoulte top-0 and removing that class of hero component fixes the problem

**Comment by antidude900** [comment]
I tried flex on layout.jsx but as hero is absolute, even flex wont work

**Comment by antidude900** [comment]
and I am certain that this change does no change to the website

**Comment by TejasNasre** [comment]
okay make changes locally and post video here please don't write messages with new chat box clear with one

**Comment by antidude900** [comment]
ok thanks

**Comment by antidude900** [comment]
Uploading Recording 2024-10-02 103529.mp4…

**Comment by antidude900** [comment]
https://github.com/user-attachments/assets/6d648a73-c484-4266-a04b-e719cc17d6cd

**Comment by antidude900** [comment]
How is it?

**Comment by TejasNasre** [comment]
> How is it?

Great Buddy Make Sure To Make Responsiveness and Change Ui Of Footer I Will Merge It then also check that when we use mobile device the color get white i think you use daisy ui ? make whole black with text white

**Comment by antidude900** [comment]
https://github.com/user-attachments/assets/359b6d52-9936-42e3-b802-dc1f6878e54f

Yeah its responsive too

**Comment by TejasNasre** [comment]
ok change color and make a PR i will merge it

**Comment by TejasNasre** [comment]
add email nexmeetup@gmail.com

**Comment by antidude900** [comment]
Ohh I have already made the pull request
