### ISSUE TITLE
Fetching info for total attendees and avg rating in the dashboard section

### ISSUE THREAD

**Issue by shreyamaheshwari1** [TejasNasre/nexmeet#102]
Currently there is no proper functionality to fetch total attendees and compute the average rating . Also the start present in the avg rating card is non functional .

**Comment by TejasNasre** [comment]
but hold this issue as of now

**Comment by prisha-sh** [comment]
hey kindly assign me this , I'll deliver asap !

**Comment by TejasNasre** [comment]
@prisha-sh already assigned bro

**Comment by TejasNasre** [comment]
@shreyamaheshwari1 i merged ui in dashboard just add functionality for the charts

**Comment by TejasNasre** [comment]
any updates ?

**Comment by TejasNasre** [comment]
any updates @shreyamaheshwari1 if you are free please update if not i will assign to other
