### ISSUE TITLE
Addition of smooth hover effects and redirect of homepage on logo click.

### ISSUE THREAD

**Issue by shobhit15082003** [TejasNasre/nexmeet#106]
There are 5 issue I would like to work on: 
1) In footer instead of logo only the project name is logo (and if you want to keep it as it is please let me know) and also when clicking on it it is not taking me to the homepage.

2) The register now button gives a jerk on hovering I can make it smooth.

3) The logos of whatsapp and twitter doen't have hover .

4) Changing the logo of twitter to X.

5) In contributors page on hover the pop up is not smooth it looks like a jerk I can make it smooth.

![Screenshot 2024-10-14 201342](https://github.com/user-attachments/assets/4197d402-e55f-48d4-8644-9b56df3e1137)

@TejasNasre plz assign me this issue.

**Comment by prisha-sh** [comment]
Hey kindly assign me this , I'll deliver asap !

**Comment by TejasNasre** [comment]
@prisha-sh already assigned

**Comment by TejasNasre** [comment]
@shobhit15082003 update the things mentioned in the above discussion

**Comment by TejasNasre** [comment]
make make pr to dev branch

**Comment by TejasNasre** [comment]
![pr](https://github.com/user-attachments/assets/2af117db-aa1c-4c90-87ac-64f1b7626f26)
read readme before do anything

**Comment by TejasNasre** [comment]
> okay add one thing bottom to top thing component like don't add in every page separately make component and add one time and fix any small changes but make sure it looks great

make this change bro

**Comment by shobhit15082003** [comment]
Ya ya I doing it....that commit was made accidentally
