### ISSUE TITLE
Implement Auto Labeler GitHub Action for Issues and PR

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#107]
- Add a new GitHub Actions workflow that triggers on issue creation and PR opening/editing.
Defined a set of keyword-label mappings to apply the appropriate labels, including:
```
Bug
Enhancement
Feature
Hacktoberfest
Hacktoberfest-accepted
GSSOC-EXT
```
Implement logic to check the title and body for these keywords and apply labels accordingly.

**Comment by mehul-m-prajapati** [comment]
@TejasNasre :

Hi,
Can I pick any feature from this list?
```
 add event reminders
 add event notifications
 add event feedback
 add event comments
 add event chat
 ```

**Comment by TejasNasre** [comment]
add comments and with authorization
