### ISSUE TITLE
Create Missing Contact Page with Sample Information

### ISSUE THREAD

**Issue by myselfshivams** [TejasNasre/nexmeet#11]
The website currently lacks a contact page, which is essential for user communication and feedback. We need to create a dedicated contact page featuring a sample contact card that aligns with the current UI style and color scheme of the website.

Labels:
- GSSoC
- Hacktoberfest

@TejasNasre Please assign this issue to me(@myselfshivams).

**Comment by TejasNasre** [comment]
@myselfshivams assigning you issue but add the whole contact page with responsiveness and  also implement feedback thing also make sure the we get data in supabase

**Comment by myselfshivams** [comment]
@TejasNasre Thank you for assigning the issue to me, @TejasNasre! I'll create a complete contact page that includes responsiveness and integrates a feedback form. I'll also ensure that we collect the data in Supabase. If I have any questions or need clarification, I'll be sure to pin you. Looking forward to getting this implemented!

**Comment by SumitSahu44** [comment]
hey @TejasNasre  assign this to me i will do it within 1hr with best quality under gssoc-ext label

**Comment by TejasNasre** [comment]
@SumitSahu44 Great Energy Give Some Time To @myselfshivams  Till Tomorrow If He Not Make Any PR You Will Get Assigned Check Out This #24

**Comment by SumitSahu44** [comment]
ok i will be wait till tommor for you

**Comment by myselfshivams** [comment]
Go ahead @SumitSahu, @Tejas please assign the task to him.

**Comment by SumitSahu44** [comment]
Thanks to assign this to me i will start working on it please add labels also

**Comment by TejasNasre** [comment]
@SumitSahu44 take time read above comments and then comment the solution with video or images and then make PR

**Comment by SumitSahu44** [comment]
NOW is this good design?

![image](https://github.com/user-attachments/assets/8c7a8ead-1611-4bc4-96c8-409ff1379e96)

**Comment by TejasNasre** [comment]
great change background color to glassmorphism  or transparent make the ui match with the current design and add this data to backend

**Comment by SumitSahu44** [comment]
ok sure i will do it
