### ISSUE TITLE
Add approval button for super admin to approve/reject events

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#110]
Currently, the NexMeet platform allows event organizers to submit events for listing. However, there is no mechanism for a super admin to approve or reject these submitted events. Implementing an approval button will enhance the event management workflow, ensuring that only vetted events are published on the platform.

**Objective**: To introduce an approval system for super admins that allows them to review submitted events and make decisions on their publication.

**Approval Button:**
Add an "Approve" and "Reject" button on the event submission review page accessible to super admins.

**Comment by TejasNasre** [comment]
add description sir

**Comment by mehul-m-prajapati** [comment]
> add description sir

added it..

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : Where is super admin user? How to login with that user locally?

**Comment by TejasNasre** [comment]
read docs : kinde Auth

**Comment by TejasNasre** [comment]
sir any updates ?

**Comment by mehul-m-prajapati** [comment]
> sir any updates ?

@TejasNasre : Can you send me any links to refer for this?
I cant find , how to login with super admin and see events

**Comment by TejasNasre** [comment]
https://youtu.be/QBadmHx7Uh0?feature=shared&t=2521

**Comment by TejasNasre** [comment]
> > sir any updates ?
> 
> @TejasNasre : Can you send me any links to refer for this? I cant find , how to login with super admin and see events

its a role base auth you will get it just watch video

**Comment by mehul-m-prajapati** [comment]
As I told you in meeting, I will push this today. You will see PR tomorrow.

**Comment by TejasNasre** [comment]
okay
