### ISSUE TITLE
[Bug]: Unable to type any value During Request Booking

### ISSUE THREAD

**Issue by inkerton** [TejasNasre/nexmeet#111]
![image](https://github.com/user-attachments/assets/9b918745-aada-488f-a1b2-e8379b0b94ac)

I dont think this is supposed to show this error. It should have a date Picker for more ease also I am unable to type anything after date. The dashes don not serve a purpose. 

@mehul-m-prajapati Please assign this issue to me

**Comment by mehul-m-prajapati** [comment]
@inkerton : I am not owner of this repo. Please go in upstream repo details and see who is managing it.

**Comment by TejasNasre** [comment]
@inkerton all correct there

**Comment by inkerton** [comment]
> @inkerton : I am not owner of this repo. Please go in upstream repo details and see who is managing it.

I am sorry I didn't knew who the admin was so I tagged the first person who came after @.

**Comment by inkerton** [comment]
> @inkerton all correct there

I didn't understood.
