### ISSUE TITLE
[Feature]: Display all events user registered for in the profile

### ISSUE THREAD

**Issue by inkerton** [TejasNasre/nexmeet#113]
![image](https://github.com/user-attachments/assets/8edccdc0-8de1-4669-a564-ab33b018285c)

I registered for an event but there is not rechecking mechanism. I was able to register for the same event again. Also, registered events are not displayed anywhere.

Please assign this issue to me, and I will work on it.

**Comment by TejasNasre** [comment]
already implemented bro check participated beside organized

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/229cf577-fa68-4d37-a8ea-8ce7697fb164)


Nothing is coming up there @TejasNasre
