### ISSUE TITLE
 Implement Missing Meta Tags, Generate Sitemap, and Create robots.txt for SEO Improvement

### ISSUE THREAD

**Issue by myselfshivams** [TejasNasre/nexmeet#12]
The current website is missing several crucial meta tags that are essential for search engine optimization (SEO). Additionally, we need to generate a sitemap and create a robots.txt file to enhance the site's visibility and crawling efficiency for search engines.

### Tasks:

1. Add Missing Meta Tags:
- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag
- Generate Sitemap:

2. Create an XML sitemap that includes all relevant pages of the website to facilitate better indexing by search engines.
Create robots.txt File:

3. Implement a robots.txt file to guide search engine crawlers on which pages to index and which to avoid.

### Labels:
- GSSoC
- Hacktoberfest

@TejasNasre  Please assign this issue to me(@myselfshivams).

**Comment by TejasNasre** [comment]
i think we have added that but some are missing

**Comment by myselfshivams** [comment]
Thanks for the update, @TejasNasre! I'll check the current implementation and identify which meta tags are missing. I'll also generate the sitemap and create the robots.txt file to ensure optimal SEO.
