### ISSUE TITLE
Implement Scroll Animation with GSAP

### ISSUE THREAD

**Issue by Mallik-vinukonda** [TejasNasre/nexmeet#121]
I am raising this issue to propose the development of smooth scroll animations using GSAP (GreenSock Animation Platform). The animations will enhance the user experience by making the page interactions more dynamic and engaging. Please let me know if you have any specific requirements or preferences regarding this feature

**Comment by TejasNasre** [comment]
it will be great if you add animations by framer motion

**Comment by Mallik-vinukonda** [comment]
Done !  I can do it

**Comment by Mallik-vinukonda** [comment]
> it will be great if you add animations by framer motion
 
Done! I'm glad to implement the animations using Framer Motion
If you have a moment, I’d love for you to check out my portfolio as well: https://mallik-portfolio.vercel.app/

Looking forward to your feedback and any further suggestions you might have!

**Comment by TejasNasre** [comment]
Can you specify were you will add animations

**Comment by TejasNasre** [comment]
And don't implement scroll triggers

**Comment by Mallik-vinukonda** [comment]
> Can you specify were you will add animations

Main Heading in the Hero Section  , and the cards below with smother transitions

**Comment by TejasNasre** [comment]
I think we don't need now if you want to add any features please go ahead no need to the animation thing now in future we will discuss

**Comment by Mallik-vinukonda** [comment]
> I think we don't need now if you want to add any features please go ahead no need to the animation thing now in future we will discuss

ok that's fine !

**Comment by TejasNasre** [comment]
Find some issue I will assign you if it's good

**Comment by Mallik-vinukonda** [comment]
> Find some issue I will assign you if it's good

ok done .
