### ISSUE TITLE
Imrove cards as the data is not visible llike date is not spotaniously catchy 

### ISSUE THREAD

**Issue by shubhagarwal1** [TejasNasre/nexmeet#122]
<img width="902" alt="Screenshot 2024-10-16 at 5 38 57 AM" src="https://github.com/user-attachments/assets/ac89c6bb-c5d3-429a-8baf-07e48f2e6d1b">

**Comment by TejasNasre** [comment]
@shubhagarwal1 sir the data will be the same we want to show but the problem is ui color thing and i think it's fine most of the thing is also depends on background image

**Comment by TejasNasre** [comment]
@shubhagarwal1 how will you solve this please eloborate

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 sir the data will be the same we want to show but the problem is ui color thing and i think it's fine most of the thing is also depends on background image

@TejasNasre yes you are right the dat ain the card is absolutly fine but the imp. heighlights are not ccatch so that is the reaso i want to revamp this an make it look more classy

**Comment by TejasNasre** [comment]
So you want to change the event card ui you can but make the info same just change the ui and post video or images here if it's good then I will merge and make the labels

**Comment by TejasNasre** [comment]
make sure to make PR to dev branch

**Comment by TejasNasre** [comment]
@shubhagarwal1 any updates ?

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 any updates ?

hey @TejasNasre can we connect i am troubling with project set up

**Comment by TejasNasre** [comment]
yeah tell me

**Comment by TejasNasre** [comment]
add bg to likes

**Comment by shubhagarwal1** [comment]
hey @TejasNasre i am not abel to create event can you please help me 
<img width="1440" alt="Screenshot 2024-10-19 at 8 54 03 PM" src="https://github.com/user-attachments/assets/5065ca35-4c75-4440-9c15-270b70e48636">
and when i create it with anothe it shows this 
<img width="946" alt="Screenshot 2024-10-19 at 8 54 50 PM" src="https://github.com/user-attachments/assets/29c7888c-ed69-4719-aa21-042a165d7f40">

i am not abel to identify the issue can you help me 
<img width="621" alt="Screenshot 2024-10-19 at 8 55 13 PM" src="https://github.com/user-attachments/assets/728639c1-08e8-4b4d-8bcc-356fae7b1ad8">

**Comment by TejasNasre** [comment]
bucket name change karo to *event_image* and data pura delete karo dataabase is ho jayega

**Comment by shubhagarwal1** [comment]
hey @TejasNasre still not abel to make it brother can we rejoin on discord

**Comment by TejasNasre** [comment]
I will be free after 11

**Comment by shubhagarwal1** [comment]
> I will be free after 11

Sure..

**Comment by shubhagarwal1** [comment]
hey @TejasNasre can we connect today, it is already 2 days now, i want ot work on the project but stuck with the set up thing 
can you please give me some of your time
