### ISSUE TITLE
REVAMP explore-event-space page as to make it more organised and clean look 

### ISSUE THREAD

**Issue by shubhagarwal1** [TejasNasre/nexmeet#123]
- update the event cards 
- view details page on cards click on event space page

**Comment by TejasNasre** [comment]
@shubhagarwal1 what's the issue describe it sir

**Comment by shubhagarwal1** [comment]
@TejasNasre as for now the event page looks good but the data and the other things could be more organized in order to make it user friendly

**Comment by TejasNasre** [comment]
make PR to dev and post video here before making ant PR

**Comment by TejasNasre** [comment]
@shubhagarwal1 any updates ?

**Comment by shubhagarwal1** [comment]
hey @TejasNasre can we connect?

**Comment by shubhagarwal1** [comment]
> yeah

discord

**Comment by TejasNasre** [comment]
come on gssoc discord general voice
