### ISSUE TITLE
Scroll to Top button 

### ISSUE THREAD

**Issue by YasirKhan231** [TejasNasre/nexmeet#126]
When we down to the website then no scroll to top button are present 

-> I add the new scroll to top button by which whne we click on that button then we go on top smooothly 

![image](https://github.com/user-attachments/assets/7c7f7364-1a4e-44b2-9861-1986299755e8)

**Comment by TejasNasre** [comment]
Already in one issue no need to it

**Comment by TejasNasre** [comment]
add this bro

**Comment by TejasNasre** [comment]
make sure to add component above the footer or where you want make PR when complete and post video here before making PR make PR to dev branch

**Comment by YasirKhan231** [comment]
ok i understand i will do changes shortly

**Comment by YasirKhan231** [comment]
that is the video 

https://github.com/user-attachments/assets/ccc63c1d-73be-4fd3-b256-15398234942b

**Comment by YasirKhan231** [comment]
should i raise pr
