### ISSUE TITLE
Custom cursor pointer 

### ISSUE THREAD

**Issue by YasirKhan231** [TejasNasre/nexmeet#127]
Unique cursor designs can capture users' attention and make the interaction, encouraging them to engage more with your content.
Please assign this to me , I am ready for this
Thankyou!

https://github.com/user-attachments/assets/5172ad72-e91d-4027-b4a0-b73a0e1335b4

**Comment by TejasNasre** [comment]
Too fancy no need

**Comment by YasirKhan231** [comment]
OK
