### ISSUE TITLE
Fevicon are not present on the website 

### ISSUE THREAD

**Issue by YasirKhan231** [TejasNasre/nexmeet#128]
The fevicon  are not present on the website 

-> I add the fevicon to the website 
![image](https://github.com/user-attachments/assets/3e6b88e2-8b6f-4cc2-8f5b-b15bc5785a2d)

**Comment by TejasNasre** [comment]
Send me the design for favicon we don't have any

**Comment by YasirKhan231** [comment]
Assign this task to me i create logo and make fevicon of it

**Comment by TejasNasre** [comment]
Please post design first sir

**Comment by TejasNasre** [comment]
@YasirKhan231 any update on design

**Comment by YasirKhan231** [comment]
please wait i will do it shortly on the design and make it

**Comment by TejasNasre** [comment]
i will give you level 3 if you design logo for favicon and main logo for website with dark and light and better from current logo
