### ISSUE TITLE
Updating Feedback Form

### ISSUE THREAD

**Issue by 0xPratikPatil** [TejasNasre/nexmeet#129]
Simplifying the feedback back and displaying responses in a table.

**Comment by 0xPratikPatil** [comment]
@TejasNasre 
As you instructed me to take only 4-5 questions for feedback, the table structure will change. How can I display the responses in the table if they are larger? Also, I need to remove the check response button for that.

**It is okay to take four or five questions from this.Let me know what you want.**

How would you rate your overall experience at the event? (Rating/Slider)
What did you enjoy most about the event? (Text Input)
What aspects of the event could be improved? (Text Input)
How likely are you to recommend this event to a friend or colleague? (Rating/Slider)
Did the event meet your expectations? Why or why not? (Yes/No + Text Input)
How satisfied were you with the event's organization? (Rating)
How was the registration process? (MCQ: Excellent, Good, Average, Poor)
Was the event well-structured and on time? (Yes/No + Text Input)
Were the event facilities (venue, seating, etc.) adequate? (MCQ: Excellent, Good, Needs Improvement)
How would you rate the quality of the speakers/presenters? (Rating/Slider)
Was the content presented by the speakers engaging and informative? (Yes/No)
Who was your favorite speaker, and why? (Text Input)
How clear were the presentations or workshops? (MCQ: Very Clear, Somewhat Clear, Not Clear)
How relevant was the event content to your interests? (Rating/Slider)
Did you learn something new or valuable at this event? (Yes/No + Text Input)
Which sessions/topics were most useful for you? (Text Input)
How can we improve the event's content for the future? (Text Input)
Did you have enough opportunities to network and engage with other participants? (Yes/No)
Was there enough time allotted for Q&A or interaction with speakers? (Yes/No)
How would you rate the networking opportunities at the event? (Rating)
Was the event location easy to access? (Yes/No)
How would you rate the event facilities (Wi-Fi, seating, catering, etc.)? (Rating/MCQ)
Were you satisfied with the communication about event logistics (venue details, schedule, etc.)? (Yes/No)

**Comment by TejasNasre** [comment]
Yeah all correct don't take all questions any 5, 4 questions will be options and 1 will be. Input text and I am but busy figure out which questions are useful to ask just think yourself and implement

**Comment by 0xPratikPatil** [comment]
Yeah, okay, I will be finalizing these as feedback questions.

What did you enjoy the most about the event?(Text Input)
How would you rate the overall organization of the event?(MCQ)
- Excellent
- Good
- Average
- Poor

How would you rate your overall satisfaction with the event? (Rating)
How likely are you to recommend this event to a friend or colleague?(Slider)
What could we improve for future events?(Text input)

**Comment by TejasNasre** [comment]
> Yeah, okay, I will be finalizing these as feedback questions.
> 
> What did you enjoy the most about the event?(Text Input) How would you rate the overall organization of the event?(MCQ)
> 
> * Excellent
> * Good
> * Average
> * Poor
> 
> How would you rate your overall satisfaction with the event? (Rating) How likely are you to recommend this event to a friend or colleague?(Slider) What could we improve for future events?(Text input)

Great mak PR after completion

**Comment by TejasNasre** [comment]
@0xPratikPatil sir any updates ?
