### ISSUE TITLE
Adding Submit Feedback form button to events page

### ISSUE THREAD

**Issue by 0xPratikPatil** [TejasNasre/nexmeet#130]
The "Submit Feedback" button will automatically become visible after the event ends. Additionally, the register button will be disabled.

**Comment by PAVAN507-STAR** [comment]
Hii @0xPratikPatil .I would love work on this issue.Can you assign me this issue?

**Comment by arbazahmed07** [comment]
hey can you please assign me this @0xPratikPatil

**Comment by 0xPratikPatil** [comment]
@PAVAN507-STAR @arbazahmed07 
That's great to see your willingness, but I have already started working on the issue and just submitted the PR late. Half of my work is already done. If you're interested, you can ask the project admin to work on the dashboard where data will be fetched from Supabase.

**Comment by TejasNasre** [comment]
> Additionally, the register button will be disabled.

its working now in production to need to this add the btn for feedback

**Comment by TejasNasre** [comment]
@0xPratikPatil sir any updates ?
