### ISSUE TITLE
JSON Parse Error in Event Page

### ISSUE THREAD

**Issue by Mallik-vinukonda** [TejasNasre/nexmeet#132]
I encountered a SyntaxError: "undefined" is not valid JSON while using the event page of the application. This error occurs when attempting to parse the event_images data with JSON.parse. It seems that some entries in the event_images field are undefined or improperly formatted, leading to this exception.

**Comment by TejasNasre** [comment]
please post images here and refer LEARN.md to setup the backend

**Comment by TejasNasre** [comment]
issue solved bro some guys posting event without images
