### ISSUE TITLE
Adding Cursor trail

### ISSUE THREAD

**Issue by Mandy1200** [TejasNasre/nexmeet#133]
As this is a very attractive and moudular website , I would like to add cursor trail for more user interface and attractive look

I will do the task with the use of HTML , CSS and JS

sample
![Screenshot (119)](https://github.com/user-attachments/assets/cf57fe4d-e909-4007-9747-d19ca9c84575)

**Comment by TejasNasre** [comment]
sir no need of this and we are using tsx with tailwindcss read the code base
