### ISSUE TITLE
Password is not present 

### ISSUE THREAD

**Issue by Aditya90456** [TejasNasre/nexmeet#135]
![Aditya90456_CodeHive and 12 more pages - Personal 2 - Microsoft​ Edge Beta 10_18_2024 4_29_04 PM](https://github.com/user-attachments/assets/c925849e-cf8f-4aa4-b0e8-57bf356ed492)
Password input is not present

**Comment by TejasNasre** [comment]
Sir we not need of password it sends OTP to authenticate the user
