### ISSUE TITLE
Bug: User is able to comment in comment section without login in website

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#138]
Bug Description: Unauthorized Guest Commenting
Issue Summary: Users are able to submit comments in the comment section of the website without being logged in, which is contrary to the expected behavior that requires authentication for commenting.

Expected Behavior: Users should only be able to comment after logging in or creating an account. Guest commenting should be restricted to maintain the integrity and quality of discussions.

**Comment by TejasNasre** [comment]
no description sir if other contributor love to work on this i will assign them @mehul-m-prajapati you have other issues to solve give chance to others 😁 just update description

**Comment by mehul-m-prajapati** [comment]
> no description sir if other contributor love to work on this i will assign them @mehul-m-prajapati you have other issues to solve give chance to others 😁 just update description

@TejasNasre : Added description

**Comment by TejasNasre** [comment]
no one is interested to take assigning you @mehul-m-prajapati
