### ISSUE TITLE
**Enhance Navbar Section: Logo Visibility in Light Mode and Content Misalignment**

### ISSUE THREAD

**Issue by ansiace** [TejasNasre/nexmeet#140]
#### Bug Description:
The navbar section currently has two issues:
1. The **logo is not properly visible** in light mode, making it difficult for users to recognize the brand.
2. The **content in the navbar** (such as home , explore ,events items) is not properly aligned, resulting in a cluttered and inconsistent user interface.

#### Current Behavior:
- The **logo** in the navbar section is hard to see in light mode due to insufficient contrast.
- The **navbar content** is not aligned, which disrupts the overall layout and UI flow.

#### Expected Behavior:
- The **logo** should be clearly visible in both light and dark modes, ensuring brand recognition in all display settings.
- The **content in the navbar** should be properly aligned to provide a clean and organized user experience.

![Screenshot 2024-10-19 000646(1)](https://github.com/user-attachments/assets/b769091a-8c5c-462e-9281-c93c4ddb9d78)

#### Suggested Fix:
- Enhance the **logo visibility** in light mode by adjusting its color, background, or contrast.
- Align the **content in the navbar** to ensure a consistent and balanced layout across different screen sizes.

**Comment by PAVAN507-STAR** [comment]
Hii @ansiace .I would like to work on this issue

**Comment by ansiace** [comment]
Hi @PAVAN507-STAR 

Thanks for showing interest in this issue! As a member of Gssoc'24 Extd! I'm actually planning to continue working on it myself

**Comment by TejasNasre** [comment]
please hold the issue as of now
