### ISSUE TITLE
Bug: bucket not found for event image

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#142]
Event should not be created if bucket fails to upload image.
---
![Animation4](https://github.com/user-attachments/assets/97544d3a-b35a-4196-a2b9-3c4054db9ddf)

---
![e2](https://github.com/user-attachments/assets/49edb1ec-7467-47cb-a7c1-25e72040d25a)

---

**Comment by TejasNasre** [comment]
sir its local host its your db  check the bucket name in supabase mine db has event_image and my column name is event_images
