### ISSUE TITLE
feature- Hey I can containerize this using the docker 

### ISSUE THREAD

**Issue by vijaykanwal90** [TejasNasre/nexmeet#144]

**Comment by vijaykanwal90** [comment]
![Screenshot from 2024-10-19 16-55-16](https://github.com/user-attachments/assets/283d9480-21bb-4e0c-870c-46fe38b56358)
![Screenshot from 2024-10-19 16-55-27](https://github.com/user-attachments/assets/db2c9002-0c41-4a84-bf78-6ece912e0fa9)
![Screenshot from 2024-10-19 16-55-34](https://github.com/user-attachments/assets/f24ce972-6150-4afe-955f-274bb137ddc5)
i will change the position of drops splasings and some missing icons

**Comment by TejasNasre** [comment]
don't change any ui

**Comment by vijaykanwal90** [comment]
ok I will add the docker file
