### ISSUE TITLE
change date picker ui

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#148]
![image](https://github.com/user-attachments/assets/1e811380-3428-4bda-ab58-d554e28f4f1f)

**Comment by shiv-0101** [comment]
Hi Tejas

Any inspiration? The whole calendar section or just the current date ui?

**Comment by TejasNasre** [comment]
Refer shadcn ui and there are some constraints that the event can't be in past so make sure this issue in calander if you interested

**Comment by bullseye4703** [comment]
Hey, I would to contribute to this repo. This would mark my first PR to HacktoberFest. So, please assign me to this issue.

**Comment by TejasNasre** [comment]
updates ?

**Comment by n-keerthi-gayathri** [comment]
@TejasNasre i want to work on this issue

**Comment by TejasNasre** [comment]
make changes asap and make PR to dev

**Comment by n-keerthi-gayathri** [comment]
@TejasNasre can you tell me in which page is it, i could not find it

**Comment by TejasNasre** [comment]
organize event route

**Comment by TejasNasre** [comment]
and update event route and many more

**Comment by TejasNasre** [comment]
@n-keerthi-gayathri any updates ? the issue is so easy

**Comment by n-keerthi-gayathri** [comment]
![image](https://github.com/user-attachments/assets/f7f1b8b5-c11a-44fa-ba10-de057f1eec66)
could not access the route in localhost. i have no idea on supabase

**Comment by TejasNasre** [comment]
make PR asap

**Comment by TejasNasre** [comment]
@n-keerthi-gayathri update ?

**Comment by n-keerthi-gayathri** [comment]
@TejasNasre i am a bit busy, need some time
