### ISSUE TITLE
Bugs : In Update Event

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#151]
When We Go For Event Updating There Are Bugs : 

![wrong data](https://github.com/user-attachments/assets/cca1019a-7e1b-4733-a41c-46eeb5f24b0f)
 
getting wrong date in registration end and start also in event start and end the date picker is buggy selecting any date.

![contact](https://github.com/user-attachments/assets/3fe750e8-9e81-4b05-ac0d-921c3756db10)

in contact the words are allowed fix

![negative price](https://github.com/user-attachments/assets/9abbf820-26e0-49ea-aecd-48801879d6fc)

negative price section 

![pop up](https://github.com/user-attachments/assets/4d1c126b-bfbc-4b8f-8f0f-92de4a4e0ecb)
  
the ui is not good in pop up

**Comment by TejasNasre** [comment]
Need to data whole edit form validation using zod and we don't want to update image

**Comment by TejasNasre** [comment]
Make PR to my dev branch before making PR post working video here

**Comment by LaibaKhalil61** [comment]
Alright!

**Comment by TejasNasre** [comment]
updates ?

**Comment by mehul-m-prajapati** [comment]
Please assign this to me
