### ISSUE TITLE
Button Box Shadow Not Displaying Correctly

### ISSUE THREAD

**Issue by KAJAL7764** [TejasNasre/nexmeet#155]
#Issues: 

Button Box Shadow Not Displaying Correctly Across Browsers

Description: 

The box shadow on the button component is not rendering as expected. Instead of appearing with a smooth shadow effect, the shadow is either too harsh, barely visible, or absent altogether.
 
![issue2](https://github.com/user-attachments/assets/31ef4c96-7222-4a03-bee2-4e3c54504edf)

Steps to Reproduce:

1. Add the following CSS to style the button element:
2. Observe the inconsistency in the box shadow's rendering.
3. The button should display a soft, subtle shadow that gives it a lifted appearance.

Level: Required level.

I request to work on resolving the button box shadow issue in the open-source project to enhance visual consistency and user experience.
Could you assign me this project.

Thanks!!

**Comment by TejasNasre** [comment]
it will fix when development of other issue
