### ISSUE TITLE
event calendar page with add to calendar functionality (an addon to explore events page )

### ISSUE THREAD

**Issue by soham-khedkar** [TejasNasre/nexmeet#157]
Yo bro i did event-calendar a specific calendar with all events listed and with desciption and add to calendar button everything is responsive and works perfectly here even if you dont login and register for the event you still can add the event to calendar . Remaining feature to add to calendar on registration will do later.....  
see this video below of implementation
https://github.com/user-attachments/assets/d9e38d0d-a2bd-4265-9729-713cd4561d50

**Comment by soham-khedkar** [comment]
ser let me know what you think of this ......

**Comment by TejasNasre** [comment]
Great Buddy 😁

**Comment by TejasNasre** [comment]
But add it on appropriate place in 2 place like on home page and in explore page

**Comment by soham-khedkar** [comment]
oh home page too...ok

**Comment by TejasNasre** [comment]
make PR

**Comment by soham-khedkar** [comment]
done!
