### ISSUE TITLE
New Page Addition | FAQs and Forum Page | User Can Also Post

### ISSUE THREAD

**Issue by Shariq2003** [TejasNasre/nexmeet#158]
I want to implement the FAQs and Forums Page with Following Functionalities:-

1. Add a new FAQs Forums Page.
2. FAQs section with Listing of FAQs on Nexmeet.
3. Forum Section with Listing of User's Posts in a Grid of Cards with Flip Effect on Cards.
4. User can also Post.
5. Sorting Functionality.
6. Responsive UI.

Please assign this to me under GSSOC Ext.

**Comment by TejasNasre** [comment]
Sorry but as of now we want want this instead of this you can test whole website and find some bugs or add new functionality
