### ISSUE TITLE
UI UX Enhancements | Addition of ProgressBar | That will represent the Current Depth of the Webpage

### ISSUE THREAD

**Issue by Shariq2003** [TejasNasre/nexmeet#159]
I want to add a progress bar that will show the current depth of the webpage, just like GSSOC website

![image](https://github.com/user-attachments/assets/057676e2-0bab-4a96-8137-fccaa16eb6d6)

Look at the top, an orange line

**Comment by TejasNasre** [comment]
Please refer previous issue comment
