### ISSUE TITLE
[FEAT]: Implement Multi-Language Support for the NexMeet Event Platform

### ISSUE THREAD

**Issue by Anushka-Pote** [TejasNasre/nexmeet#166]
Description:
To enhance user experience and accessibility, we propose adding multi-language support to the NexMeet Event Platform. This feature will allow users to view the platform in their preferred language, making it more inclusive for a global audience.

How to Implement:
Language Selection: Create a dropdown menu for users to select their preferred language.
Translation Files: Set up JSON files for each language containing key-value pairs for text elements used in the application.
Dynamic Content Loading: Use JavaScript to load the appropriate translation file based on the user's selection and dynamically update the content on the page without requiring a full reload.

Why:
Implementing multi-language support will make the NexMeet platform more accessible to users from various linguistic backgrounds, potentially increasing user engagement and satisfaction. It aligns with our goal of creating an inclusive community around events.

**Comment by Anushka-Pote** [comment]
Hey, I won't be able to complete this assigned tasks due to reasons, so this issue is open for anyone to take over.

**Comment by TejasNasre** [comment]
okay

**Comment by Shariq2003** [comment]
Assign this to me

**Comment by TejasNasre** [comment]
sir make update

**Comment by Shariq2003** [comment]
> sir make update

okay, wokring

**Comment by TejasNasre** [comment]
sir je jaldi karoo

**Comment by Shariq2003** [comment]
> sir je jaldi karoo

Aaaj mil jayegi, PR
