### ISSUE TITLE
 Implement Event Tagging System for Enhanced Event Categorization

### ISSUE THREAD

**Issue by Anushka-Pote** [TejasNasre/nexmeet#167]
Description:
To improve the organization and searchability of events on the NexMeet platform, we propose adding an event tagging system. This feature will allow event organizers to categorize their events using specific tags, making it easier for users to filter and find relevant events.

Why:
Adding an event tagging system will enhance user experience by enabling easier event discovery and categorization. This feature encourages better organization of events, making it simpler for users to find what they're interested in.

**Comment by TejasNasre** [comment]
Already added tags and filter please specify

**Comment by Anushka-Pote** [comment]
Oh...So tags I just saw it, so my bad 
But in filters I meant filters by "upcoming", "Most liked", "price range" or "Mode" sort of filters so it's easy to navigate via events

**Comment by TejasNasre** [comment]
i think no need of tag as of now add any other functionality
