### ISSUE TITLE
Sort By Price | Events should also be sortable by their price value.

### ISSUE THREAD

**Issue by Shariq2003** [TejasNasre/nexmeet#169]
There are only two options for sorting the events:-
1. Lowest Likes.
2. Highest Likes.

There should also be an option "Sort by price value"

https://github.com/user-attachments/assets/05406b38-4519-4b4f-a024-ab50c3da38ef

**Comment by Shariq2003** [comment]
@TejasNasre, could you please assign this to me.

**Comment by TejasNasre** [comment]
updates ?

**Comment by Shariq2003** [comment]
Will raise PR by 2am tonight

**Comment by TejasNasre** [comment]
Fix #139

**Comment by TejasNasre** [comment]
I will assign you make different PR For That

**Comment by Shariq2003** [comment]
Okay @TejasNasre sir, I will fix this after getting free of college

**Comment by Shariq2003** [comment]
> I will assign you make different PR For That

@TejasNasre sir, this PR already fixed the issue #139.
