### ISSUE TITLE
Undefined Username | Minimum Length Validation Alert for Comments

### ISSUE THREAD

**Issue by Shariq2003** [TejasNasre/nexmeet#170]
1. On commenting on any event, there should be a validation for a minimum comment length.
2. When a user (not logged in) comments on an event, the username will be undefined, instead of Showing Guest User.
3. Popup Alerts for Commenting Status (Success/Failure).

https://github.com/user-attachments/assets/2bde87a9-e1fe-4abe-bc00-048ac2ea23b7

**Comment by Shariq2003** [comment]
@TejasNasre, this issue should be implemented, i think, if u think same, then please assign this to me.

**Comment by TejasNasre** [comment]
can you connect once now on vc gssoc

**Comment by mehul-m-prajapati** [comment]
@Shariq2003 : How are you bro? Are you working on 30+ issues at same time? 
Can you come one general channel?

**Comment by TejasNasre** [comment]
@mehul-m-prajapati ajaoo

**Comment by Shariq2003** [comment]
> @Shariq2003 : How are you bro? Are you working on 30+ issues at same time? Can you come one general channel?

No, I can work on a single issue at a time, but try finish min 3-5 issues in a day
