### ISSUE TITLE
event active bug

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#174]
![image](https://github.com/user-attachments/assets/c0c77239-12ac-4d46-983c-7379027a940b)

current the registration date is end but the event is active the btn section works properly fix the active tag

**Comment by Ryadav0654** [comment]
Hi @TejasNasre ,

I would like to work on this issue. Could you please assign it to me?

Thank you!

**Comment by TejasNasre** [comment]
please connect once on discord (general vc gssoc )when you are free message me here

**Comment by TejasNasre** [comment]
updates ? i will give you level 2 if you do this : in event page there is a active and inactive things its not working properly so you want to do if the 1) current date is in between registration date then it should be active 2) if the current date is after the end date then it will show inactive 3) if the current date is before event registration date then want to show upcoming thus the below btn should also work if the current date is between then the btn should work if after then registration ends and before the registration upcoming

**Comment by TejasNasre** [comment]
@Ryadav0654 if you can work on this do fast till night or i will assign to other

**Comment by Ryadav0654** [comment]
@TejasNasre, I'm working.
