### ISSUE TITLE
Rewape Event Details Page [UI]

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#178]
https://www.proelevate.in/event/codemod-kickstart-2-391359

Refer the above ui add icons and if you can make more great ui than that page it's great.

Expected time to make PR : till tomorrow morning 

Use react - icons or lucide- react for icon

Don't change can Functionality just add ui

**Comment by Neel-07** [comment]
can this issue be assigned to me

**Comment by TejasNasre** [comment]
Make sure to submit PR till tomorrow morning and Make PR to dev branch it's easy issue make sure to cover all edge cases light mode and dark mode use colour that can grab attention but theme vahe kahoo

**Comment by TejasNasre** [comment]
@Neel-07 make PR asap

**Comment by TejasNasre** [comment]
this issue is already raised and make PR jis ka ui acha and structure acha rahega us ka merge honga

**Comment by SupriyaGo** [comment]
I would like to try this UI @TejasNasre

**Comment by TejasNasre** [comment]
go @SupriyaGo 😂

**Comment by TejasNasre** [comment]
make PR tonight refer https://www.proelevate.in/event/codemod-kickstart-2-391359 and add your creativity

**Comment by TejasNasre** [comment]
sir pr merged  already
