### ISSUE TITLE
[BUG]: Default Event Count Display Issue on Login

### ISSUE THREAD

**Issue by PrityanshuSingh** [TejasNasre/nexmeet#181]
### What happened?
When a user logs in to the dashboard, the "Total Events" count is displayed as 19 by default, even if there are no events found. This causes a misleading display of the total number of events, as the correct default value should be 0 events when no events are associated with the user.

### What did you expect to happen?
The default event count should be displayed as 0 when no events are found, accurately reflecting the user's event history.

![image](https://github.com/user-attachments/assets/b054ad70-9836-4281-a6f8-837714ee956c)

Please assign this issue to me under gssoc-ext level2 and hactoberfest-accepted, @TejasNasre  , as I am interested in working on it.

**Comment by TejasNasre** [comment]
i will assign you if you write functionality for all the analytics in dashboard

**Comment by TejasNasre** [comment]
@PrityanshuSingh ????

**Comment by PrityanshuSingh** [comment]
> @PrityanshuSingh ????

I was travelling for a day, will try to create a PR today.

**Comment by TejasNasre** [comment]
@SupriyaGo i think @PrityanshuSingh will raise PR

**Comment by TejasNasre** [comment]
@SupriyaGo look here #166
