### ISSUE TITLE
UI/UX Enhancements

### ISSUE THREAD

**Issue by kekubhai** [TejasNasre/nexmeet#19]
The user viewpoint is foremost important thing for any dev , the project looks really good . But I figured the first impression can be made better add more colours and dividing the sections so that the user gets a clear idea of what is in it. Some of the Improvisations i observed  are ;
 Navbar : 
![image](https://github.com/user-attachments/assets/91e14f53-1971-4fc2-acd4-fa872b7d781d)
This navbar gets merged with the body and may the user doesn't get an eye on it. 
FAQ : 
![image](https://github.com/user-attachments/assets/cd03c3a8-2d3f-4c24-892b-61fd743777b3)
This sections doesn;t divied the questions and the answers in a clear cut manner. Maybe adding different colours can do justice. 
  Also Adding a Toggle bar at the Top to Change dark and Light theme will greatly improvise the User's Experience. 
 These are some of my suggestions. Tell me which one would you like and Add some more if you have suggestions. 
I would Like to Work on these, Please assign me in here

**Comment by TejasNasre** [comment]
Okay fix the themes we want black and white not white full but around white so add the toggle btn and make the change in ui whole project

**Comment by kekubhai** [comment]
Just to make sure. Should I just add the toggle theme option only ? Or can I do the other designs too which I mentioned above. Also will find something around white which matches the ui. 
 Please assign me the issue. I'll start working now . 
Thanks

**Comment by TejasNasre** [comment]
Just to the Google theme with whole ui black or white don't do other thing mentioned above by you as for now

**Comment by kekubhai** [comment]
Started working on it .

**Comment by TejasNasre** [comment]
Make initial state black

**Comment by TejasNasre** [comment]
Yeah I will add whole supabase guide setup today at 11 give me some time.

UI is fine but the text should be white in black and text black in white

**Comment by kekubhai** [comment]
Yeah sure .  Do you want such theme toggle button in events pages too ? 

Sure will try to resolve the texts.

**Comment by TejasNasre** [comment]
bro the theme toggle btn will be everywhere and if you change from one side it will reflect all example : https://gamegrid-six.vercel.app/ use zustand for global state management

**Comment by kekubhai** [comment]
Okay I get it, But the problem is with the Beams. If you can somehow Appy the beams effects in alll the pages it will be automatically Applied.

**Comment by TejasNasre** [comment]
Why you changed the beams effect we want only for the hero page

**Comment by TejasNasre** [comment]
Please make a video what have you done

**Comment by kekubhai** [comment]
Sure, It will just take some time. Hope it is Fine by you.

**Comment by TejasNasre** [comment]
@kekubhai any updates ?

**Comment by kekubhai** [comment]
Sorry man I was a little caught up with exams. Will come back to it within a day. Please bear with me

**Comment by TejasNasre** [comment]
@kekubhai any updates ?

**Comment by kekubhai** [comment]
yes, I am done Sorry for being  so late . Check this here ; https://www.loom.com/share/71b0cbcd68f84db5990b356c70d94f11?sid=b1578e66-63f9-42cc-b60b-e51dd412e14c
Thanks

**Comment by TejasNasre** [comment]
you messed up every thing the hero page should be 100vh and i said to make the whole site change the theme what are you doing man the btn should border black in white theme and you changed the bg-color or hero page to gray fix it or i will assign the issue to other

**Comment by kekubhai** [comment]
yeah fine

**Comment by TejasNasre** [comment]
@kekubhai any updates its easy issue bro tomorrow will be last day otherwise assigning to other

**Comment by kekubhai** [comment]
Give it to someone else
