### ISSUE TITLE
add language translator 

### ISSUE THREAD

**Issue by ananyag309** [TejasNasre/nexmeet#198]
add language translator using google api which will make the project more user friendly even to native users

**Comment by Shariq2003** [comment]
PLease assign this to me.

**Comment by TejasNasre** [comment]
please look #166 make sure to use global state management and makes changes

**Comment by ananyag309** [comment]
@TejasNasre yes sure please assign this issue to me

**Comment by TejasNasre** [comment]
already 166 has issue i am closing this now
