### ISSUE TITLE
Fix Logo Alignment and Visibility in Nexmeet Community Partner Section

### ISSUE THREAD

**Issue by Rahilsamani** [TejasNasre/nexmeet#199]
I noticed that the logos under the Navneet Community Partner section are not properly centered, which affects the overall layout. Additionally, the Next.js logo is not visible. I would like to help by addressing these issues to enhance the visual consistency of the page.

https://github.com/user-attachments/assets/f4c57126-959a-4ef1-bb07-8ed2d9301797

**Comment by TejasNasre** [comment]
bhai ye navneet kya hai bhai
