### ISSUE TITLE
Add Filtering On Client Side - Category, Date, Likes 

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#2]
**Currently Data Is Fetching From Supabase So Add The Filtering After Fetching Data By Category , Date , Likes**

**Comment by milan567** [comment]
Hi @TejasNasre. I would like to help you on this project by resolving this issue. If you are ok with it you can assign me the issue.

**Comment by TejasNasre** [comment]
Hey @milan567 Great 😃 

Please Feel Free To Make The Changes

Happy Coding

**Comment by milan567** [comment]
Hi @TejasNasre. Is it here missing a env file in the project? Can you help me with instructions how to run it.

**Comment by TejasNasre** [comment]
KINDE_CLIENT_ID=71c799b764434ede93ef2041225b8aa3
KINDE_CLIENT_SECRET=yxsgLCyZy4sP5RwwjCOORpvhkzUJTxq4DGFMOlE3ILc9i6BPd6
KINDE_ISSUER_URL=https://nexmeetup.kinde.com
KINDE_POST_LOGIN_REDIRECT_URL=http://localhost:3000/dashboard

NEXT_PUBLIC_SUPABASE_PASSWORD=KUY30YPnYE2FgADG
NEXT_PUBLIC_SUPABASE_URL=https://jzhgfowuznosxtwzkbkx.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aGdmb3d1em5vc3h0d3prYmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ0MjUwNzYsImV4cCI6MjA0MDAwMTA3Nn0.1LSpyCNYTK08v8MFr7hj1cLkL0zZFhp1EHfXAaS3MKI

**Comment by TejasNasre** [comment]
I will be sharing sample env with you soon

**Comment by TejasNasre** [comment]
Step 1 : Start The Repo
Step 2 : fork the repo 
Step 3 : clone the forked repo
Step 4 : git branch <your branch name>
Step 5 : git checkout <your branch name>
Step 6 : make changes and git push to your branch
Step 7 : make a PR with compare with dev branch and your branch

I will check and merged 😁
