### ISSUE TITLE
addition of a professional logo

### ISSUE THREAD

**Issue by Nvntdad** [TejasNasre/nexmeet#20]
i want to add professional looking logo to the website. please assign this task to me under the gssoc and hacktoberfest programme.

**Comment by TejasNasre** [comment]
Assign you but don't make logo using ai or other thing if you are really interested and have a skills please make it by your own and by looking towards the problem the level of this issue will be depends on your logo now

**Comment by Nvntdad** [comment]
sure i am a professional graphic designer as well, so i will try my best.
