### ISSUE TITLE
make a new page by which new community partners can contact us to make them partner in nexmeet

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#202]
- take relevant info in form
- make db in supabase
- after successfully form submission nexmeetup@gmail.com should get the mail with all info
- make frontend
- use zod for validation 
- make use to add toast messages 
- after completing form from one email the person should get the you already applied for community partnership

**Comment by shubhagarwal1** [comment]
Hey @TejasNasre please assign me this task
