### ISSUE TITLE
UI - Dark/light theme related issues

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#205]
## 1. Bug: theme toggle does not highlight Profile dropdown options
![Animation4](https://github.com/user-attachments/assets/ec71175f-25d5-41df-82dd-d66388f21ab0)
---
## 2. Bug: The dark theme is selected after a refresh, even if the light theme was chosen before.
![Animation4](https://github.com/user-attachments/assets/2ed0e864-c271-4fd5-9303-43035f883fb0)
---
## 3. Bug: Date Picker not visible in dark theme
![c1](https://github.com/user-attachments/assets/fbab266f-6154-4d98-8225-aec00916db87)

---
## 4. Bug: Organised button color hides text in light theme
![c2](https://github.com/user-attachments/assets/a171700e-5468-44af-9348-a78a9a5f3533)

**Comment by TejasNasre** [comment]
Fix all bugs but cover all edge case  sir

**Comment by TejasNasre** [comment]
update sir ?
