### ISSUE TITLE
Maps API integration when choosing event location

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#206]
![c2](https://github.com/user-attachments/assets/1750666a-da60-4c8c-b69a-7098221464af)

**Comment by TejasNasre** [comment]
You wanna do this

**Comment by mehul-m-prajapati** [comment]
yes, sir @TejasNasre

**Comment by TejasNasre** [comment]
sir update on this

**Comment by jassBawa** [comment]
@TejasNasre can I do this and exactly what we want here only countries or proper address..?

**Comment by TejasNasre** [comment]
@jassBawa  proper address 

 @mehul-m-prajapati is okay to assign him

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : yes, you can assign him

**Comment by TejasNasre** [comment]
@jassBawa make PR asap
