### ISSUE TITLE
Add Lottifiles animation to website or use some spline3d/threejs mockups to  make ui look great 

### ISSUE THREAD

**Issue by soham-khedkar** [TejasNasre/nexmeet#213]
LottieFiles has free plugins or you can design by your own it acts as a plugin in framer check that out and try to make something out of it . You can use spline its easy to integrate that but it should really be able to go with the design flaws..
![image](https://github.com/user-attachments/assets/f4606433-fbfc-4c99-9265-6e7b3c0e4c57)

**Comment by TejasNasre** [comment]
What's happening here
