### ISSUE TITLE
fix the hover shadow of buttons, seperator in faq section and logo visible in light mode 

### ISSUE THREAD

**Issue by soham-khedkar** [TejasNasre/nexmeet#216]
See this video:
https://github.com/user-attachments/assets/3bfff0f2-355c-46f4-a88f-2e0ba7eb3cf9

Also make logo in footer flex flex-col items-center in parent div

**Comment by TejasNasre** [comment]
The FAQ section will fix

**Comment by fikirWalle** [comment]
Hi, could you assign this to me? I'm new to the project and would love to work with you. I'm from GSSC 24 Extend.

**Comment by TejasNasre** [comment]
@fikirWalle make pr asap

**Comment by fikirWalle** [comment]
sure,Thanks. Before I create the PR, I just want to confirm — you want the logo above the social media icons, right? That’s centered, I guess.

**Comment by soham-khedkar** [comment]
> sure,Thanks. Before I create the PR, I just want to confirm — you want the logo above the social media icons, right? That’s centered, I guess.

yup the one in the footer component
