### ISSUE TITLE
Profile dropdown bug

### ISSUE THREAD

**Issue by soham-khedkar** [TejasNasre/nexmeet#217]
Fix this for mobile devices and also position theme toggle icon on top left 

![image](https://github.com/user-attachments/assets/6120e27c-12cd-4cb4-86d4-7a265e836227)

**Comment by KrinsKumar** [comment]
Hey can I work on this, also whats exactly the issue in the mobile devices, just the theme icon?

**Comment by soham-khedkar** [comment]
Position of theme icon and drop-down  of profile on mobile device is the issue see the screenshot above

**Comment by KrinsKumar** [comment]
sounds good, please assign this issue to me if possible!!.

**Comment by TejasNasre** [comment]
make PR asap

**Comment by KrinsKumar** [comment]
I will start working on this and raise a PR. Is there a way I can get the env variables, or do I have to generate them myself?

**Comment by TejasNasre** [comment]
refer learn.md
