### ISSUE TITLE
Payment gateway integration

### ISSUE THREAD

**Issue by soham-khedkar** [TejasNasre/nexmeet#218]
This is the main stuff we want to get done for initially launching this easily and letting users get on this platform. You can use razorpay payment gateway for this , but user should only be able to pay once event organiser accepts their registration and locks it that is when user sees pay now button . So more work is added you need to add feature of locking registration of a particular participant and then let the participant pay the event fee.

**Comment by TejasNasre** [comment]
I am thinking not to add payment gateway now instead of it when we take event details we add functionality that if the event is paid we show the option to add the value and the organiser will add there scanner and we take transaction I'd

**Comment by soham-khedkar** [comment]
we can do that but if i need to update my upi qr every other time i decide to take money in some different account might get little annoying and we have no control over qr not working and transaction failures because acknowledgement of successful transaction is necessary

**Comment by soham-khedkar** [comment]
lets hear if some contributor has better ideas...

**Comment by soham-khedkar** [comment]
yeah if qr is implemented we should have that alert popup that it cant be edited later and acknowledgment of payment success as a feature should be added for the organiser

**Comment by shubhagarwal1** [comment]
Hey @TejasNasre please assign me this task.

**Comment by TejasNasre** [comment]
https://nexmeet-lake.vercel.app/community-patnership

**Comment by TejasNasre** [comment]
sir je ye kar do jaldi

**Comment by shubhagarwal1** [comment]
> sir je ye kar do jaldi

Yes @TejasNasre you can assign this to other contributors as this is getting delayed bhai, I really applolozise for such thing, i am 30% done with the thing, have setted up tables and wrote toggle for price change for selecting free or paid. Estimating i will be completing this by 30/oct/2024

**Comment by TejasNasre** [comment]
okay do that make PR on 30

**Comment by shubhagarwal1** [comment]
Hey @TejasNasre as this is getting delayed due to changes requested, on time, so will close this issue for now, and will take this in next release.
