### ISSUE TITLE
Adding a logo for the website

### ISSUE THREAD

**Issue by aarch34** [TejasNasre/nexmeet#222]
![image](https://github.com/user-attachments/assets/4875e840-343c-40f5-8126-bc90348b4b4e)
the website has the default logo, I want to add a different logo which matches the websites aesthetics.
please assign me this issue \.
@TejasNasre

**Comment by TejasNasre** [comment]
i will assign you make the logo first

**Comment by aarch34** [comment]
![image](https://github.com/user-attachments/assets/ca414625-a4dd-4127-8801-515a5bbdc1c0)
how does this look after i convert it into a favicon?
@TejasNasre

**Comment by TejasNasre** [comment]
acha hai ji

**Comment by TejasNasre** [comment]
![IMG_20241027_163532](https://github.com/user-attachments/assets/79da0bed-a88b-402f-9974-ae0fe233fea8)
Can you redesign this Stuff

**Comment by TejasNasre** [comment]
Also main design of the nexmeet logo

**Comment by TejasNasre** [comment]
I am not taking about only the favicon i need new logo design and also want to change the seo image so you can change the logos all 3 and make changes to code I will give you level 3

**Comment by aarch34** [comment]
okay do you have any specifications? also since you want me to redesign all the logos, can i take a week atleast?

**Comment by TejasNasre** [comment]
Not have any specifications just make the logo aligned with the solution We are providing and needs to look great we have only 3 days ser not a week

**Comment by aarch34** [comment]
okay can i submit by 30 night or 31st morning? i have my exams for 3 days

**Comment by TejasNasre** [comment]
Okay 👍 you can submit anytime but the gssoc  point will not count that's why I am saying the project is open source if you have exams then to later not problem but in a week or make till 31 night 7 pm your choice

**Comment by aarch34** [comment]
hi, please check discord
