### ISSUE TITLE
VIP : Data Visualization 

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#227]
![analytisc](https://github.com/user-attachments/assets/61ecf8e9-3bd4-473d-ad53-b34938802ae9)
here we implemented ui with recharts but add the logic to visualize the data the user has and add default state for the visualization

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : please assign this to me

**Comment by mehul-m-prajapati** [comment]
total event count and categories in chart

**Comment by TejasNasre** [comment]
sir  ji update

**Comment by TejasNasre** [comment]
sir any updates ?

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : See PR #262
