### ISSUE TITLE
Add Community Listing Page

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#230]
- Add Community Listing Page Like A Explore Event Page

- The Community Should First Approve By Super Admin 

- First Exposed The Route To Add Community
- Take Some Good Info About There Community And Take Relevant Info
- The User Can Join There Community Pages By Submitting User Info

**Comment by mehul-m-prajapati** [comment]
[@samya](https://github.com/samyak-aditya) : are you interested?

**Comment by samyak-aditya** [comment]
Hey @TejasNasre Assign me this issue

**Comment by TejasNasre** [comment]
Update?

**Comment by TejasNasre** [comment]
@samyak-aditya any updates ?

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : please assign it to me if nobody is working on it

**Comment by TejasNasre** [comment]
go ahead  sir , gssoc end ho gaya kya ?

**Comment by mehul-m-prajapati** [comment]
extended until 10th nov @TejasNasre .

You can add more issue now.

**Comment by TejasNasre** [comment]
okay sir

**Comment by TejasNasre** [comment]
@mehul-m-prajapati sir ji updates ?

**Comment by mehul-m-prajapati** [comment]
Will update you on VC today

**Comment by TejasNasre** [comment]
okay are you available now if yes pin me on dm

**Comment by mehul-m-prajapati** [comment]
yes, let's connect in general vc
