### ISSUE TITLE
Add seprate contributor page

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#24]
Add the contributors page where shows the realtime contributors list and add starts forked and graphs if possible and other things and links to Contribution

**Comment by 0xSaurabhx** [comment]
im intrested in working on it.

**Comment by TejasNasre** [comment]
make PR when complete on dev branch

**Comment by TejasNasre** [comment]
@0xSaurabhx any updates ? make PR today

**Comment by 0xSaurabhx** [comment]
Made New PR with Updates.
