### ISSUE TITLE
Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [TejasNasre/nexmeet#246]
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

**Comment by TejasNasre** [comment]
We have contact us page we can use as a feedback no need seprate as of now will look in upcoming days
