### ISSUE TITLE
Add Event Statistics to Organizer Dashboard

### ISSUE THREAD

**Issue by pranavbafna586** [TejasNasre/nexmeet#25]
**Description:**
Add a statistics section to the organizer dashboard to provide insights into event performance.

**Features:**
1. **Total Registrations**: Show the total number of event registrations.
2. **Attendee Demographics**: Display breakdown by location and age group.
3. **Engagement Rate**: Percentage of users interacting with event content.
4. **Revenue (if applicable)**: Total revenue from ticket sales.
5. **Event Feedback**: Average rating from attendee feedback.

**Tech:**
- Use Chart.js or shadcn/ui for visualization.

**Priority:** High
**Type:** Enhancement

Could you please assign this issue to me under GSSOC'24 extd, hacktoberfest programme?

**Comment by TejasNasre** [comment]
We have build the graph thing

**Comment by TejasNasre** [comment]
![Screenshot_2024-10-03-20-34-49-08](https://github.com/user-attachments/assets/15d04b43-00f1-4f5a-bb95-e40c16016a49)
![Screenshot_2024-10-03-20-34-56-95](https://github.com/user-attachments/assets/a434a04e-1008-492b-aef4-cee5c7c78725)

**Comment by TejasNasre** [comment]
By using recharts

@pranavbafna586 but you can add more functionality as you mentioned in issue

**Comment by TejasNasre** [comment]
@pranavbafna586 i edited the setup instructions on LEARN.md checkout and Make PR

**Comment by TejasNasre** [comment]
@pranavbafna586 any updates

**Comment by pranavbafna586** [comment]
yes working on it will post it by tomorrow.

**Comment by pranavbafna586** [comment]
Hey @TejasNasre I had designed the ui but i have replaces majar parts of dashboard ui is it ok or should I only add the following comonents
1) Total Registrations: Show the total number of event registrations according to age group **Radial Chart**
2) Attendee Demographics: Display breakdown by location **Pie Chart - Interactive**
3) Engagement Rate: Percentage of users interacting with event content. **Line Chart**
4) Revenue (if applicable): Total revenue from ticket sales. **Bar Chart**
5) Event Feedback: Average rating from attendee feedback. **Bar Chart - Custom Label**

**Comment by TejasNasre** [comment]
post video here

**Comment by TejasNasre** [comment]
@pranavbafna586 don't change the ui fully

**Comment by pranavbafna586** [comment]
![image](https://github.com/user-attachments/assets/5fd4f45c-9e87-4155-81b0-4d732384a317)

**Comment by TejasNasre** [comment]
Okay Look Nice what it shows if the account ie new and the middle one please explain

**Comment by pranavbafna586** [comment]
![image](https://github.com/user-attachments/assets/a8ef36a1-0030-4a8b-a47a-f6066d02d457)

as of now the data is static 
1) Total Registrations on hover the tooltip will display the registration
2) Attendee Demographics is categorizing the registration in basis of location.
3) Engagement Rate

**Comment by TejasNasre** [comment]
don't put static data

**Comment by pranavbafna586** [comment]
Actually I didn't found database modules so from. Where should I take data

**Comment by TejasNasre** [comment]
setup your supabase and kinde auth refer LEARN.md

**Comment by TejasNasre** [comment]
@pranavbafna586 any updates ?

**Comment by TejasNasre** [comment]
I will check and specify you on which basis you need to add the analytics will take some time from my side

**Comment by TejasNasre** [comment]
the last two engagement rate i don't know how we calculate it just add ui for that and avg rating will be decided on feed back just add ui of that also as of now

**Comment by TejasNasre** [comment]
make PR to dev by run: npm run build
