### ISSUE TITLE
Offline First Experience with Caching and Sync Status Indicator

### ISSUE THREAD

**Issue by tarunkumar2005** [TejasNasre/nexmeet#255]
### Offline First Experience with Caching and Sync Status Indicator

In today’s digital environment, users often encounter connectivity issues, which can disrupt their interaction with a website or application. Implementing an "Offline First" approach could greatly improve user experience, especially for those accessing the platform in areas with intermittent internet access. 

The idea is to integrate offline support in the app, ensuring users can still browse core content and access cached data even when they temporarily lose connectivity. By using service workers to cache essential assets and certain frequently accessed data, we can ensure that the application remains accessible and performs smoothly offline. Additionally, we’ll implement a **Sync Status Indicator** to keep users informed about their connectivity state. This status component can display whether they’re online, offline, or in a syncing state, helping them better understand the app's behavior. 

For example, consider a platform similar to YouTube. Offline capabilities would allow users to load recent data or static content even if their connection is unstable, making for a seamless experience. The sync status indicator adds transparency, showing users when their content is being updated or when the app is operating with cached data.

This enhancement would add significant reliability to the application, benefiting a wide range of users, and setting the project apart from others that don’t offer offline functionality.

@TejasNasre  Assign this to me under GSSoC 2024 Ext and Hacktoberfest. I will work on this issue.

**Comment by TejasNasre** [comment]
Go ahead sir make PR to dev branch asap and post video here before making PR

**Comment by TejasNasre** [comment]
@tarunkumar2005 any updates ?

**Comment by tarunkumar2005** [comment]
@TejasNasre will put the video before 5 or 6pm today only working on it.

**Comment by tarunkumar2005** [comment]
https://github.com/user-attachments/assets/383f8b18-63aa-4782-b6bf-7728db416758

Here is the video check it out and please put this PR a level 3.

**Comment by tarunkumar2005** [comment]
@TejasNasre

**Comment by TejasNasre** [comment]
Make the UI look good and with theme dark and white I will merge this with l3

**Comment by TejasNasre** [comment]
@tarunkumar2005 you are working on it ?

**Comment by tarunkumar2005** [comment]
@TejasNasre Will do till evening share updated video.

**Comment by TejasNasre** [comment]
Sir any updates?

**Comment by tarunkumar2005** [comment]
@TejasNasre Sorry bro i was busy today so forgot about it will definitely put the video tomorrow.

**Comment by tarunkumar2005** [comment]
https://github.com/user-attachments/assets/3ebc6082-4166-407d-ac28-f55cb8090d4d

**Comment by tarunkumar2005** [comment]
@TejasNasre Check now

**Comment by TejasNasre** [comment]
make pr to my dev branch i will review and merge
