### ISSUE TITLE
Add Event Feedback Feature

### ISSUE THREAD

**Issue by 0xPratikPatil** [TejasNasre/nexmeet#26]
**Description:**
We propose adding a new feature to the NexMeet platform that allows event attendees to provide feedback after attending an event. This feature will enable organizers to gather insights on the event's success and areas for improvement.

**Feature Details:**
**Purpose:**
To collect feedback from attendees once the event concludes.
Provide organizers with detailed reports on attendees' satisfaction and suggestions for future improvements.

**Feedback Form:**
Create a form accessible to event attendees.
Include fields like rating (1-5 stars), text feedback, and suggestions for improvement.
Optionally, provide a section for anonymous feedback.

**Security & Privacy:**
Ensure all feedback data complies with relevant privacy policies (GDPR, etc.).
Feedback should be stored securely, with appropriate access controls.

**Priority: High**
**Type: Enhancement**

Could you please assign this issue to me under GSSOC'24 extd, Hacktoberfest programme?

**Comment by TejasNasre** [comment]
@0xPratikPatil Great Can You Please Share Me Workflow And Approach

**Comment by 0xPratikPatil** [comment]
@TejasNasre 
**1. Define Feedback Requirements:**
Form Customization: Admins should be able to define various types of input fields for feedback forms based on event types.
Input Fields: TextInput, Rating, Slidebar, Multiple Choice Questions (MCQs).

**2. Design Database Schema (Supabase):**

**Feedback Table:**

feedback_id (Primary Key)
event_id (Foreign Key)
user_id (Foreign Key)
inputs (JSON object storing dynamic input values)
created_at (Timestamp)
Form Configuration Table:

form_id (Primary Key)
event_type (Type of event)
inputs (Array of input configurations, each with type, label, options for MCQs, etc.)

**3. API Endpoints (Next.js API Routes):**
POST /api/feedback: Submit feedback.
Request Body: { event_id, user_id, inputs }
Response: Success/Error message.

GET /api/feedback/:event_id: Fetch feedback for an event.
Response: Array of feedback objects.

GET /api/forms/:event_type: Fetch form configuration for a specific event type.
Response: Form configuration object.

**4. Frontend Implementation:**
A. Admin Interface:
Form builder to create and customize feedback forms.
Save form configurations to the database.
B. Feedback Form for Attendees:
Dynamically generate form based on configuration fetched from /api/forms/:event_type.
Input Field Components:
TextInput: For open-ended feedback.
Rating: For star ratings.
Slidebar: For range inputs.
MCQ: For multiple-choice questions.

C. Submit Feedback:
Collect input values and submit to /api/feedback endpoint.
5. Feedback Analysis Dashboard for Organizers:
Fetch feedback data from /api/feedback/:event_id.
Display feedback with options for sorting and filtering.
Visualize feedback with charts and summaries.
Workflow Steps:

Admin Customizes Feedback Form:
Use an admin interface to build and configure feedback forms.
Save the configuration (form structure) to Supabase.
Generate Feedback Form:

On event page load, fetch the relevant form configuration from /api/forms/:event_type.
Render form dynamically using the fetched configuration.

Submit Feedback:
Collect input values from the form.
Submit the collected data to the /api/feedback endpoint.

Display Feedback to Organizers:
Fetch feedback data for a specific event using /api/feedback/:event_id.
Display the feedback data on the organizer's dashboard with options to filter, sort, and visualize the data.

**Addition Info:**
1. I found that there is no database, so I am creating a new issue for building Prisma + Supabase (no auth).
2. There is no role-based authentication right now, so I will create that for all users.
3. The naming convention for APIs and database variables might differ from here.
4. For now, I will be working on the feedback form frontend, and afterward, the backend APIs for CRUD operations. 
5. kindly assign this issue to me.

Let me know about the changes.

**Comment by TejasNasre** [comment]
Great Don't user server make things possible in client side itself its easy by the way

**Comment by 0xPratikPatil** [comment]
@TejasNasre 
Table For Event Space Img Vid :
create table
  public.event_space_img_vid (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    url text not null,
    event_space_id uuid not null,
    constraint event_space_img - vid_pkey primary key (id),
    constraint event_space_img - vid_event_space_id_fkey foreign key (event_space_id) references event_space (id)
  ) tablespace pg_default;

1.I cant create this table on supabase.The error in your SQL statement is due to the incorrect use of dashes (-) in the constraint names.
2.I am also unable to provide full access to the tables on Supabase.

**Comment by TejasNasre** [comment]
you setup now by fixing from your side  i will fix it soon

**Comment by 0xPratikPatil** [comment]
@TejasNasre 

https://github.com/user-attachments/assets/d764db38-8704-4ba1-bc6d-f7574e893822

**Comment by TejasNasre** [comment]
great job deserve level3 but has some bugs no worries will solve in upcoming days
