### ISSUE TITLE
Fix minor issues

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#267]
- Remove the additional line when hovering on navbar
- Less padding less b/w navbar buttons
- Filter Graphs by organizer on dashboard page

**Comment by TejasNasre** [comment]
sir fix this i will merge this i merged pervious PRs

**Comment by mehul-m-prajapati** [comment]
Okay, I will open PR before 7pm

**Comment by TejasNasre** [comment]
Sir you are fixing this ?

**Comment by mehul-m-prajapati** [comment]
I will do it after the program

**Comment by TejasNasre** [comment]
sir fix dashboard graphs

**Comment by TejasNasre** [comment]
also add that definition for communities and storage setup

**Comment by mehul-m-prajapati** [comment]
open issues with description

**Comment by adityadafe** [comment]
add favicon too

**Comment by mehul-m-prajapati** [comment]
closing because of no response

**Comment by TejasNasre** [comment]
Sir ji response kya chahiye? App PR maro na

**Comment by TejasNasre** [comment]
Ye fix kardo bs

**Comment by mehul-m-prajapati** [comment]
> also add that definition for communities and storage setup

???

**Comment by TejasNasre** [comment]
> > also add that definition for communities and storage setup
> 
> ???

I changed the whole thing now so no need of that now just fix that minor fixes it's important now

**Comment by TejasNasre** [comment]
Sir pr maro jaldi

**Comment by TejasNasre** [comment]
@mehul-m-prajapati sir ji ajj kardo
