### ISSUE TITLE
Add super admin page with button to approve/reject communities

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#269]
Currently, the NexMeet platform allows create communities. However, there is no mechanism for a super admin to approve or reject these submitted communities. 
Implementing an approval button will enhance the event management workflow, ensuring that only vetted events are published on the platform.

**Comment by TejasNasre** [comment]
yeah i want it

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : please assign the same
