### ISSUE TITLE
Bug: Nexmeet Community Partner image loading

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [TejasNasre/nexmeet#272]
in your website at home page in Nexmeet Community Partner this section the Next Js image is not rendering i want to fix this.

![WhatsApp Image 2024-11-09 at 02 26 24_319e4a63](https://github.com/user-attachments/assets/ff6681b4-83b8-415a-9779-a3a41cab0c35)

**Comment by Fahad-Dezloper** [comment]
@TejasNasre Created a pull request after solving this issue check it out please
