### ISSUE TITLE
Added multiple language support system

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [TejasNasre/nexmeet#274]
i want to implement multiple language support system for your website to scall it globally for other region and cultural country that's will bring audience through all over country

**Comment by TejasNasre** [comment]
Make a change langauge selection in footer it will be fixed there and also add the local storage the langauge selection and it should change the langauge of whole website okay

**Comment by TejasNasre** [comment]
Make sure to make PR tomorrow and on dev branch
