### ISSUE TITLE
feat: custom cursor

### ISSUE THREAD

**Issue by itznayan** [TejasNasre/nexmeet#28]
Description: Implement a custom cursor with hover effects and mix-blend-mode: difference. The cursor should change dynamically based on the background it hovers over, creating a unique interactive experience.

Custom Cursor: Replace the default cursor with a custom shape (e.g., circle, icon).
Hover Effect: Smoothly transition the cursor's appearance when hovering over elements (e.g., change in size or color).
Mix Blend Mode: Apply mix-blend-mode: difference to ensure the cursor dynamically contrasts with the background.

Feature :

Custom cursor replaces the system cursor globally or on specific elements.
Hover triggers visual changes (size, shape, or color).
mix-blend-mode: difference works seamlessly across modern browsers.
Ensure smooth performance on all devices and provide fallbacks for unsupported browsers.

**Comment by itznayan** [comment]
hey @TejasNasre please assign this issue to me under GSSOC'24 .

**Comment by TejasNasre** [comment]
no need of custom cursor its too fancy and its not feature bro
