### ISSUE TITLE
[FEAT REQ]: When I want to share event with someone it would be great if OG image show up

### ISSUE THREAD

**Issue by adityadafe** [TejasNasre/nexmeet#281]
![image](https://github.com/user-attachments/assets/23fe9737-55a2-42ce-bce0-134dca001960)

Like these -
![image](https://github.com/user-attachments/assets/6b308e86-b055-4e84-ad13-f927db6d416f)

**Comment by TejasNasre** [comment]
It's showing sir

**Comment by TejasNasre** [comment]
![Uploading IMG_20241126_091526.jpg…]()

**Comment by TejasNasre** [comment]
![IMG_20241126_091526](https://github.com/user-attachments/assets/27ae82a6-fd36-4309-8d62-74509b2430da)

**Comment by TejasNasre** [comment]
If you want to add this you can other we will be doing that
