### ISSUE TITLE
add events to the gogle calendar

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#32]
add event to google calendar after click to save event to google calendar after user register for event

**Comment by ParasY1724** [comment]
Please assign this task to me

**Comment by TejasNasre** [comment]
@ParasY1724 please share the approach how you will solve this

**Comment by TejasNasre** [comment]
@ParasY1724 you want to work on this issue or not ?

**Comment by ParasY1724** [comment]
@TejasNasre  I would like to work , i had previous worked on same 
Apporch :
Using Google Calendar API on Google Console Cloud.
Once the use is registered we can call that api.

**Comment by ParasY1724** [comment]
I will start working as soon as  task is assigned to me.

**Comment by TejasNasre** [comment]
@ParasY1724 make sure the option will be visible after user register for specific event

**Comment by TejasNasre** [comment]
@ParasY1724 any updates ?

**Comment by ParasY1724** [comment]
@TejasNasre i am done with implementation of main code, now integration with main project and testing is remaining . Will send PR today .

**Comment by TejasNasre** [comment]
send video ? and merge with dev branch

**Comment by TejasNasre** [comment]
@ParasY1724 any updates ?

**Comment by ParasY1724** [comment]
Sorry Sir , I am unable to continue this issue

**Comment by TejasNasre** [comment]
no worries 😀

**Comment by rudrapratap63** [comment]
@TejasNasre , could you please assign this issue to me? I will complete it by tomorrow. Additionally, could you provide more details about the issue?

**Comment by TejasNasre** [comment]
what additional info you want you can ask me

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : if nobody is working on this, then you can assign it to me.

**Comment by rudrapratap63** [comment]
@mehul-m-prajapati I am working on this issue and tomorrow I will send PR.
