### ISSUE TITLE
Change Twitter Symbol to X in footer section

### ISSUE THREAD

**Issue by Amanjayswal500** [TejasNasre/nexmeet#34]
I would like to propose a change to update the Twitter symbol to "X"  to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users. please assign this issue to me

![Screenshot 2024-10-05 023330](https://github.com/user-attachments/assets/22971062-dc25-4a19-9379-5b37192953cb)

**Comment by TejasNasre** [comment]
Please don't make this type of issues we have a great project please look other problems
