### ISSUE TITLE
[Level1 Enhancement] Add Github Greetings Bot!

### ISSUE THREAD

**Issue by KiranBaliga** [TejasNasre/nexmeet#41]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by TejasNasre** [comment]
@KiranBaliga make the greeting message funny and like something with assigns our idea

**Comment by KiranBaliga** [comment]
@TejasNasre Please review the PR and action accordingly. Details added in the PR. Thank you 🙏
