### ISSUE TITLE
Delete Event Handling and Toast Showing for deleted or added or edited events.

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [TejasNasre/nexmeet#43]
We can use Shadcn components for Toasts.

**Comment by SunkaraboinaPraveenKumar** [comment]
Can i work on it ?

**Comment by TejasNasre** [comment]
repeated issue request

**Comment by TejasNasre** [comment]
the PR is not raised yet i will confirm till tomorrow and i will assign you if the feature have not done
