### ISSUE TITLE
Contact Us Page Empty

### ISSUE THREAD

**Issue by Ahsankhalid618** [TejasNasre/nexmeet#45]
I'd like to add a "Contact Us" which is empty right now, page that includes:

![image](https://github.com/user-attachments/assets/3fa31385-1400-4125-88fe-db062624d5c1)

- A functional contact form

- Interactive elements

- A location map

**Additionally, I will design the UI design for the page.**

Could you please assign me this issue?

_Labels_: **Gssoc, level3, Hacktoberfest**

**Comment by TejasNasre** [comment]
i am assigning you and give you level3 if you add all functionality and the feedback should be integrated though the supabase   and this A functional contact form

Interactive elements

A location map

Additionally, I will design the UI design for the page.

**Comment by Ahsankhalid618** [comment]
Yeah, sure. I am starting to work on it now.

**Comment by TejasNasre** [comment]
before pushing make sure post video here and make PR to dev and run : npm run build before pushing

**Comment by Ahsankhalid618** [comment]
A new Contact Form was added, Full functionality was implemented, Supabase integration for feedback, Email functionality with Resend was implemented for Feedback, and a map was added to the Contact Page. 

https://github.com/user-attachments/assets/0c45b0dd-284a-450e-ad33-bc4de32bdf2d

Supabase Integration for feedback form successfully Implemented!

![Screenshot 2024-10-10 014008](https://github.com/user-attachments/assets/3dd21601-545c-4335-95a2-0b7edaac7ee6)


Build Successful 

![Screenshot 2024-10-10 015412](https://github.com/user-attachments/assets/29b09e9f-e2c9-4cd2-811e-d9a83b8c9b16)

**Comment by TejasNasre** [comment]
Great Make PR to dev

**Comment by TejasNasre** [comment]
Make sut

**Comment by TejasNasre** [comment]
@Ahsankhalid618 you setup your resend with own domain smtp or just testing with there initial template

**Comment by Ahsankhalid618** [comment]
@TejasNasre I’ve set up the resend process so that all you need to do is add your API key in the .env file. Once that’s done, the feedback messages will be automatically routed to the SMTP server associated with your API key.

**Comment by TejasNasre** [comment]
i know but it allows only few emails is we have lot of users then i will not work make PR we will solve later email thing if you want to solve you can make new issue i will assign you

**Comment by Ahsankhalid618** [comment]
okay i will solve it in next issue.

**Comment by AyushSharma72** [comment]
> i know but it allows only few emails is we have lot of users then i will not work make PR we will solve later email thing if you want to solve you can make new issue i will assign you

you can use nodemalier to send as many email as you want
