### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by CharVaibhav** [TejasNasre/nexmeet#46]
I would like to desgn and add favicon to the website. Please assign me this task

**Comment by TejasNasre** [comment]
show me design

**Comment by CharVaibhav** [comment]
**Here a few designs, let me know if u want to make any changes**

![Black and Grey Clean Modern Minimalist Creative Technology Logo](https://github.com/user-attachments/assets/f3987bb0-b9be-4266-9f42-cf74c629259a)
![Brain tech logo design  smart brain logo design](https://github.com/user-attachments/assets/afeb198b-7faf-4ba2-9969-bf0df874823c)
![letter N tech logo design template](https://github.com/user-attachments/assets/0e7fb295-2307-4848-b31a-4c665b78791e)
![Letter N Abstract shape Logo](https://github.com/user-attachments/assets/ecfd883e-09d8-48a2-8105-3eb3e333c88b)
![Pink and Purple Gradient Tech Abstract Logo](https://github.com/user-attachments/assets/23c2e0e1-0fe9-4e44-a595-af3bcfb20f16)
![Colorful Modern Infinity Technology Free Logo](https://github.com/user-attachments/assets/4bdb3b81-fb5a-4085-8121-2dd1cd79acb6)

**Comment by TejasNasre** [comment]
no matching with solution and problem its ai generated  i think

**Comment by CharVaibhav** [comment]
How would you like me to design it?

**Comment by TejasNasre** [comment]
i don't have design idea make it by your own

**Comment by ronit-ghosh** [comment]
![Uploading logo.jpg…]()

**Comment by ronit-ghosh** [comment]
![logo](https://github.com/user-attachments/assets/56699668-5734-402f-87af-adf31253f444)

**Comment by TejasNasre** [comment]
@soham-khedkar look here and guide if possible

**Comment by soham-khedkar** [comment]
Oh ok I think anyone who wanna do this favicon issue do the logo too don't use just ai try to keep it simple name of the website won't help meaning should come out of what you make like for example Google meet uses a camera make something related for like NextGen meetups and events ig...

**Comment by TejasNasre** [comment]
need to change logo ? i think its okay

**Comment by soham-khedkar** [comment]
Idk I think it can be more different if it looks good to you then no issues..mostly websites use miniature version of logo as favicon

**Comment by soham-khedkar** [comment]
Idk I think it can be more different if it looks good to you then no issues..mostly websites use miniature version of logo as favicon
