### ISSUE TITLE
To not be able to register if the registration date has been passed for an event.

### ISSUE THREAD

**Issue by RchtDshr** [TejasNasre/nexmeet#47]
**Describe the bug**  
Currently, users are allowed to register for events that have already occurred. This causes confusion, as users should not be able to register for an event if the registration deadline or the event date has passed.

1. Open the app and navigate to the events section.  
2. Find an event that has already happened (i.e., the event date or registration deadline is in the past).  
3. Attempt to register for that event.  
4. Observe that the app allows registration even though the event has already taken place.

**Expected behavior**  
When an event's registration deadline has passed or the event has already occurred, the registration option should be disabled. Users should receive a message that registration is closed for that event.

**Screenshots before**  
![image](https://github.com/user-attachments/assets/e32c4fbe-9a69-4710-9f12-d7d676e6873f)

**Fix**  
Disable the registration button and inform the user that the registrations for that specific event has been closed.

**Comment by TejasNasre** [comment]
add one more thing in event register page here : https://nexmeet-lake.vercel.app/add-event  we can choose the past date as well its a bug fix it

**Comment by RchtDshr** [comment]
okay, on it
