### ISSUE TITLE
Implementation For Request Booking At Event Space

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#49]
We have event space at dashboard then explore events and under that request booking for the space i made the schema for supabase check LEARN.md you just need to make the form and run insert query on it.

Make PR to dev and post video before make PR

**Comment by rudrapratap63** [comment]
@TejasNasre  Please Assign this issue to me so I'll start by creating the form and running the insert query as mentioned.

**Comment by rudrapratap63** [comment]
@TejasNasre Just to confirm, what do you mean by "Make PR to dev and post video before make PR"? Are you referring to recording a video walkthrough of the changes before submitting the PR? Please let me know so I can follow the correct process.

**Comment by TejasNasre** [comment]
Yeah recording the walkthrough video

**Comment by rudrapratap63** [comment]
@TejasNasre Ok sir I will try to do my best.

**Comment by TejasNasre** [comment]
@rudrapratap63 any updates ?

**Comment by rudrapratap63** [comment]
![image](https://github.com/user-attachments/assets/aa451c68-782c-458e-ba30-6ad915a33238)

@TejasNasre, for confirmation, when the user clicks the Request Booking button, they will be redirected to a new form page where the form will have the following inputs:
- Organizer ID
- Space ID
- Request Date
- Status

There will also be a Submit Request button. When the user clicks the Submit Request button, we will run the insert query on it.

**Comment by TejasNasre** [comment]
Yes

**Comment by rudrapratap63** [comment]
@TejasNasre I think in your learn.md documentation there is two typo error so can you please check this .
![image](https://github.com/user-attachments/assets/3fa7e863-b063-448f-90be-301b1a0f6afe)
instead of this : 
```
 constraint event_space_img - vid_pkey primary key (id),
 constraint event_space_img - vid_event_space_id_fkey foreign key (event_space_id) references event_space (id)
```
it should be like this: 
 ```
constraint event_space_img_vid_pkey primary key (id),
 constraint event_space_img_vid_event_space_id_fkey foreign key (event_space_id) references event_space (id)
```

**Comment by rudrapratap63** [comment]
@TejasNasre, when the user clicks the `Submit Request`  button, where should we redirect the user: to the explore-events page or the home page?

**Comment by TejasNasre** [comment]
> @TejasNasre, when the user clicks the `Submit Request` button, where should we redirect the user: to the explore-events page or the home page?

Redirect to dashboard

**Comment by rudrapratap63** [comment]
Ok I will change and redirect to the dashboard

**Comment by rudrapratap63** [comment]
@TejasNasre , please check the [PR](https://github.com/TejasNasre/nexmeet/pull/70). I have now redirected the user to the dashboard when they click the request-booking button.
