### ISSUE TITLE
Feature : Review section UI changed

### ISSUE THREAD

**Issue by VinayLodhi1712** [TejasNasre/nexmeet#50]
I want to change the UI design of Review section.

![already reviw](https://github.com/user-attachments/assets/6957ba66-daec-448e-ab19-6d775d2df9ba)

I wanted to show review like cards and real review with website suitable design
![review hai](https://github.com/user-attachments/assets/74daf935-cd04-4858-b239-b20968d5541a)

**Comment by TejasNasre** [comment]
No need of this as of now
