### ISSUE TITLE
Incorrect team size and duration values are being entered in the database

### ISSUE THREAD

**Issue by shreyamaheshwari1** [TejasNasre/nexmeet#51]
Hii PA,
When i create an event and enter the team size and duration of my event if I check in the console the values that have been populated in the database are different from the ones I provided in the placeholder field . That is lets say I am entering a taeam size of 4 it automatically becomes 1 in the database for some reason . There is a need to fix this issue.

**Comment by TejasNasre** [comment]
this will fix by the form validation thing issue already raised
