### ISSUE TITLE
Make UI /UX enhancement 

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#52]
- add toggle theme btn with working changing theme globally and by tailwind css 
- make the light theme beautiful
- add the star and github link to project in landing here page to show this project is open source 
-  refer  : https://gamegrid-six.vercel.app/

**Comment by amitroy-thedev** [comment]
Hey @TejasNasre i want to work on the issue but before that would clarify that where all the changes i means css are that i will change ?

**Comment by amitroy-thedev** [comment]
and the dark/night mode will be applied to all the pages?

**Comment by TejasNasre** [comment]
yes that's why i gave level 3 and also the light theme should look good

**Comment by iamsaura8h** [comment]
@TejasNasre i can work on dark mode button and its functionality

**Comment by TejasNasre** [comment]
@iamsaura8h assigning you but need till  tomorrow and read above comments to clarify issue

**Comment by iamsaura8h** [comment]
@TejasNasre on it !

**Comment by TejasNasre** [comment]
> @TejasNasre on it !

Make PR as soon as possible

**Comment by inkerton** [comment]
Can I work on it ??? @TejasNasre It has been more than 3 days

**Comment by TejasNasre** [comment]
@inkerton assigning you make PR asap and read all the comments what are requirements also make PR to dev branch post video here before make a PR

**Comment by TejasNasre** [comment]
@inkerton make PR till tonight

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/a0203f0e-8e3e-4809-9cf0-8ac8b9b52d63)


These stars??

**Comment by TejasNasre** [comment]
> @TejasNasre ok sure I will work on it before that please specifu what u want here 'add the star and github link to project in landing here page to show this project is open source' . To display the number of stars a github repo has ?

Bhai issue kya hai tu kya bol raha and the refrence is the theme only you can add this thing also in landing page it's open source starts and fork
