### ISSUE TITLE
TypeError: Cannot Read Properties of Null (reading 'default')

### ISSUE THREAD

**Issue by antidude900** [TejasNasre/nexmeet#6]
I got his error when trying to sign up. It asked for verification code on g-mail and when i submitted the code, it redirected me to dashboard where I got this error:

![image](https://github.com/user-attachments/assets/ea147f34-7f4a-4af8-987a-2d181764a915)

Upon inspecting the browser console, I got this:

![image](https://github.com/user-attachments/assets/1dd66d50-2df1-4047-ac93-065729299e91)

I think this error occurred while trying to read properties of user object.

I would love to help resolve this issue.

**Comment by TejasNasre** [comment]
resolve this issue @antidude900

**Comment by TejasNasre** [comment]
when user is signing with email verification the dashboard gives error fix it

**Comment by TejasNasre** [comment]
i fixed it

**Comment by antidude900** [comment]
Yeah I couldn't even get the project running due to the build issue.  So will I get any points for this?😆

**Comment by TejasNasre** [comment]
sorry not on this we have a great  problem solving project make a new features and find bugs

**Comment by TejasNasre** [comment]
> Yeah I couldn't even get the project running due to the build issue. So will I get any points for this?😆

its because of project setup issue i will solve it soon i am not getting time to add setup😅

**Comment by antidude900** [comment]
Btw what was the problem?

**Comment by TejasNasre** [comment]
not have any problem, we are building project on supabase  so i need to give you whole architecture then you will be able to run it and for auth you can setup using kinde auth

**Comment by TejasNasre** [comment]
add that footer till tomorrow

**Comment by antidude900** [comment]
Ok, btw the [LEARN.md](https://github.com/TejasNasre/nexmeet/blob/main/LEARN.md) file is missing in Readme

**Comment by TejasNasre** [comment]
> Ok, btw the [LEARN.md](https://github.com/TejasNasre/nexmeet/blob/main/LEARN.md) file is missing in Readme

yeah i will added it soon give me some time 😑

**Comment by antidude900** [comment]
sorry😅
