### ISSUE TITLE
Adding toast notification during log in ,log out and sign up

### ISSUE THREAD

**Issue by Amnyadav** [TejasNasre/nexmeet#64]
as there is no toast like notification pops up when user get logged in or logged out.
to provide better user experience it is necessary to have these toast notification

@TejasNasre can you assign me these task

**Comment by TejasNasre** [comment]
how you will do it i don't think its important  we are using kinde auth

**Comment by Amnyadav** [comment]
By using a npm package .
It is kind of notification you have seen it in many websites for example gfg .
Whenever you logged in or logged out a pop like msg is appeared on a specific location where you decide

**Comment by TejasNasre** [comment]
but bro we are using kind auth they manage state it self no need of this feature as of now please look to other issues
