### ISSUE TITLE
Edit Event

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#7]
There Is Edit Event Page But Some Values Are Not Previewing Like Default Dates And Image Fix Whole Page (Edit Event).

**Comment by antidude900** [comment]
I can do that! Give this issue to me.

**Comment by TejasNasre** [comment]
you are working on different issue i will assign only one at a time.

**Comment by akashkumar30698** [comment]
> you are working on different issue i will assign only one at a time.

@TejasNasre can you assign me this?

**Comment by TejasNasre** [comment]
@akashkumar30698 Yes

**Comment by TejasNasre** [comment]
@akashkumar30698 I have setup the LEARN.md check out and please make PR

**Comment by TejasNasre** [comment]
@akashkumar30698 please make PR or i will remove you by assigned

**Comment by shreyamaheshwari1** [comment]
Hii @TejasNasre could you please assign this to me under gssoc extended and hactoberfest . I am willing to fix this bug

**Comment by TejasNasre** [comment]
assigning you @shreyamaheshwari1 make PR when completed with dev branch and make sure before PR you should post video here of working feature

**Comment by shreyamaheshwari1** [comment]
sure @TejasNasre .
Thank you.

**Comment by Amnyadav** [comment]
hey @TejasNasre can you assign these issue to me ?

**Comment by TejasNasre** [comment]
already assigned @Amnyadav

**Comment by shreyamaheshwari1** [comment]
Hii @TejasNasre will complete by today night and send the video

**Comment by TejasNasre** [comment]
okay

**Comment by shreyamaheshwari1** [comment]
Hii @TejasNasre here is the required video which shows the default details that the user provided while creating an event alongwith the restructured edit event page . Is it alright? If yes I can raise the pr otherwise I can do the required changes.


Uploading vc (1).mp4…

**Comment by shreyamaheshwari1** [comment]
Hii @TejasNasre here is the required video which shows the default details that the user provided while creating an event alongwith the restructured edit event page . Is it alright? If yes I can raise the pr otherwise I can do the required changes.

https://github.com/user-attachments/assets/32df2d74-593d-4a01-be48-3b4e7011357c

**Comment by shreyamaheshwari1** [comment]
@TejasNasre kindly review this for any changes or recommendation.

**Comment by TejasNasre** [comment]
great @shreyamaheshwari1

**Comment by TejasNasre** [comment]
make PR with dev branch and before push run : npm run build if have any error remove then push

**Comment by TejasNasre** [comment]
@shreyamaheshwari1 make PR

**Comment by shreyamaheshwari1** [comment]
@TejasNasre do i need to make a pr to the dev branch and not the main branch?

**Comment by TejasNasre** [comment]
Dev Branch

**Comment by shreyamaheshwari1** [comment]
Yes I raised the pr . Kindly review it @TejasNasre . Thank you!
