### ISSUE TITLE
Changing the twitter logo to new X logo

### ISSUE THREAD

**Issue by tarunkumar2005** [TejasNasre/nexmeet#77]
Changing the twitter logo to new X logo

@TejasNasre Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by TejasNasre** [comment]
i will ban you and probably all open source repo will ban you bro just find some valuable issue

**Comment by tarunkumar2005** [comment]
Don't get angry bro if you don't want say no every other repo has given this issue to people

**Comment by TejasNasre** [comment]
> Don't get angry bro if you don't want say no every other repo has given this issue to people

yeah pollute open source issue like that

**Comment by TejasNasre** [comment]
> Don't get angry bro if you don't want say no every other repo has given this issue to people

i am not angry just telling you do not this for points make some meaningful contribution

**Comment by tarunkumar2005** [comment]
if you don't want it just say no and why saying me spam and polluting see my PRs and all in the other repos you repo is only trash nothing to do in that that's why i raised these issues.

**Comment by tarunkumar2005** [comment]
see the faults in yourself what you have done till now i have taken time contributing to the peoples project but no one has done like this

**Comment by tarunkumar2005** [comment]
I don't wanna contribute to a repo like this trash and nothing to do in which i am at top 15 very much better than you are and those points are gained by the proper contributions because other repos have good issues to solve you don't have issues to solve then not my fault and don't ever say to me spam and polluting, you are polluting this here my making a project like this in gssoc and demotivating people here they see what other issues are there and try to raise where it is not done but no worries i don't have any more to say.

**Comment by tarunkumar2005** [comment]
Keep your repo to yourself and play with it don't wanna contribute to it.
