### ISSUE TITLE
Add Strong Form Validations With Error Message

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#8]
The Form In Event And In Event Space Has Less Validation And No Error Messages If Any Add This In Both Forms.

**Comment by antidude900** [comment]
How about using Zod for validation?

**Comment by TejasNasre** [comment]
I used zod earlier but I thinks it's okay but sometimes after filling correct form the is not submitting to supabase. You can try if sucessful I will merge it.

**Comment by TejasNasre** [comment]
you are working on different issue i will assign only one at a time.

**Comment by antidude900** [comment]
Can I get this issue now?

**Comment by trishap-16** [comment]
can you assign me to this issue

**Comment by TejasNasre** [comment]
@antidude900 you don't want to work on this issue ?

**Comment by trishap-16** [comment]
i want to work on it

**Comment by TejasNasre** [comment]
@trishap-16 assigning you make sure to make it perfect and take time if you want but do it perfect

**Comment by antidude900** [comment]
Sorry, I wont be able to continue contributing. Something important has come up that requires my attention right now.

**Comment by TejasNasre** [comment]
@trishap-16 any updates ?

**Comment by TejasNasre** [comment]
@trishap-16 make PR till tomorrow or i will assigned other contributor

**Comment by LaibaKhalil61** [comment]
@trishap-16 are you talking about the organise event form? There is no other event related form I saw on the website

**Comment by ShubhamKadam098** [comment]
Hey i would love to work on this issue.

**Comment by TejasNasre** [comment]
make PR when completed and with dev branch make sure before PR you post video here

**Comment by TejasNasre** [comment]
@ShubhamKadam098 tomorrow will be last day of your PR otherwise i will remove you

**Comment by ShubhamKadam098** [comment]
Hey @TejasNasre, 

Sorry for the late reply, I was busy with other work. I've almost finished the changes and have attached a video. However, I'm facing some issues during testing. Once I resolve them, I'll push the changes. I should be able to push them by tomorrow.


https://github.com/user-attachments/assets/11630863-46a1-47eb-93ba-34300d44aaa6

**Comment by TejasNasre** [comment]
Okay there was a bug that the number cab be negative resolved this also

**Comment by TejasNasre** [comment]
make PR bro

**Comment by ShubhamKadam098** [comment]
Hey @TejasNasre , 
I apologize for the late reply. I’ve finished the changes and attached a video for you to review. Could you please take a look and let me know if it’s okay to proceed with the PR?


https://github.com/user-attachments/assets/04ee0791-c78b-41a8-a7dd-2ba59b280c95
