### ISSUE TITLE
Github Workflow : Notify Contributors When Pull Requests Are Merged

### ISSUE THREAD

**Issue by samyak-aditya** [TejasNasre/nexmeet#81]
Notify Contributors When Pull Requests Are Merged

### Issue Description
**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

**Comment by samyak-aditya** [comment]
Hey @TejasNasre   Please assign me this issue with "level3"

**Comment by TejasNasre** [comment]
> Hey @TejasNasre Please assign me this issue with "level3"

That's not possible to assign you this issue with level 3

**Comment by samyak-aditya** [comment]
Okay then assign this with level2

**Comment by TejasNasre** [comment]
I will assign you but at level 1 and you have to solve both issues at single PR and explain more about auto labels

**Comment by samyak-aditya** [comment]
If you want me to close both issue in single or assign me level3

**Comment by TejasNasre** [comment]
It's not possible it's very easy issue

**Comment by samyak-aditya** [comment]
Atleast assign level2 ?
