### ISSUE TITLE
Run the Stats

### ISSUE THREAD

**Issue by haseebzaki-07** [TejasNasre/nexmeet#83]
I want to transition these stats present at the "Trusted by eCommerce Businesses" section of the project by starting them from 0 to the current count. This makes them look more appealing and attractive because stats show the creadibility of a website.

![Screenshot 2024-10-13 114145](https://github.com/user-attachments/assets/d182ed2c-9dcd-4f79-9a19-3cc4d3ace3e1)

**Comment by TejasNasre** [comment]
Okay but change the content as well we are not e commerce and trusted by them so add content align with our solution

**Comment by TejasNasre** [comment]
Make PR to dev  and run : npm run build before committing any changes and before raising PR post working video here

**Comment by haseebzaki-07** [comment]
sure @TejasNasre I will follow the workflow
