### ISSUE TITLE
Pop Up Component 

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#9]
Add Custom Success , Error  Or Other. Add Component  With Pop Up And Make Ui Better Don't Use React Toast If Using It Make Better Ui.

**Comment by Eshan05** [comment]
Hello, I can work on this
Instead of React Toast will shadcn sonner be fine with you? Or are you thinking of a component from scratch?

**Comment by akashkumar30698** [comment]
> Add Custom Success , Error Or Other. Add Component With Pop Up And Make Ui Better Don't Use React Toast If Using It Make Better Ui.

 @TejasNasre can you assign me this work

**Comment by TejasNasre** [comment]
> > Add Custom Success , Error Or Other. Add Component With Pop Up And Make Ui Better Don't Use React Toast If Using It Make Better Ui.
> 
> @TejasNasre can you assign me this work

Sorry @akashkumar30698 i need to assign the issue to @Eshan05 on FCFS basis

**Comment by TejasNasre** [comment]
@Eshan05 you can add shadcn component but shows custom messages with color you got it i think add pop up in the whole website where they need like after submitting the event show "successfully submit event"   with green or any color but implement in whole thing i will label this level3 issue if you are up to work on this issue

**Comment by Eshan05** [comment]
> @Eshan05 you can add shadcn component but shows custom messages with color you got it i think add pop up in the whole website where they need like after submitting the event show "successfully submit event" with green or any color but implement in whole thing i will label this level3 issue if you are up to work on this issue

Works with me, I will give sufficient color indication on the toasts. The component supports custom messages and all so it won't be a problem.
Also yes I will add in all places necessary like and make it match the UI. You can assign it to me I'll add any updates/clarifications here

**Comment by Eshan05** [comment]
Hello @TejasNasre can you see if the style works with you?
![firefox_tXKWnNCTLv](https://github.com/user-attachments/assets/2daa08e1-4d9c-4d55-be3e-ab32e36c4f7f)

**Comment by TejasNasre** [comment]
Okay but make it on top user can't see on bottom every time and make sure how it's works on mobile devices

**Comment by Eshan05** [comment]
> Okay but make it on top user can't see on bottom every time and make sure how it's works on mobile devices 

On mobile devices it appears centered with ~80% width, actually considering mobile only I kept it at bottom so it doesn't interfere. I can make it more noticeable so user can notice it

**Comment by TejasNasre** [comment]
Okay 👍🏻
