### ISSUE TITLE
In profile page => User name, email id and logout should be dropdown options in navbar profile icon

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TejasNasre/nexmeet#93]
![p1](https://github.com/user-attachments/assets/cce0c8ab-15ca-4f5b-b49d-a0333d907aea)

**Comment by TejasNasre** [comment]
I think is not need it will make ui more conjugated there

**Comment by mehul-m-prajapati** [comment]
> I think it's not need it will make ui more complex there in header

okay, then you can close this issue.
